/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.routines;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;

import uk.co.raubach.weatherstation.server.database.codegen.WeatherstationDb;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatsDaily extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 724232773;

    /**
     * The parameter <code>weatherstation_db.stats_daily.startDate</code>.
     */
    public static final Parameter<Date> STARTDATE = Internal.createParameter("startDate", org.jooq.impl.SQLDataType.DATE, false, false);

    /**
     * The parameter <code>weatherstation_db.stats_daily.endDate</code>.
     */
    public static final Parameter<Date> ENDDATE = Internal.createParameter("endDate", org.jooq.impl.SQLDataType.DATE, false, false);

    /**
     * The parameter <code>weatherstation_db.stats_daily.windFactor</code>.
     */
    public static final Parameter<Double> WINDFACTOR = Internal.createParameter("windFactor", org.jooq.impl.SQLDataType.FLOAT, false, false);

    /**
     * Create a new routine call instance
     */
    public StatsDaily() {
        super("stats_daily", WeatherstationDb.WEATHERSTATION_DB);

        addInParameter(STARTDATE);
        addInParameter(ENDDATE);
        addInParameter(WINDFACTOR);
    }

    /**
     * Set the <code>startDate</code> parameter IN value to the routine
     */
    public void setStartdate(Date value) {
        setValue(STARTDATE, value);
    }

    /**
     * Set the <code>endDate</code> parameter IN value to the routine
     */
    public void setEnddate(Date value) {
        setValue(ENDDATE, value);
    }

    /**
     * Set the <code>windFactor</code> parameter IN value to the routine
     */
    public void setWindfactor(Double value) {
        setValue(WINDFACTOR, value);
    }
}
