/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.routines;


import java.sql.Timestamp;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

import uk.co.raubach.weatherstation.server.database.codegen.WeatherstationDb;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatsDaily extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>weatherstation_db.stats_daily.startDate</code>.
     */
    public static final Parameter<Timestamp> STARTDATE = Internal.createParameter("startDate", SQLDataType.TIMESTAMP(0), false, false);

    /**
     * The parameter <code>weatherstation_db.stats_daily.endDate</code>.
     */
    public static final Parameter<Timestamp> ENDDATE = Internal.createParameter("endDate", SQLDataType.TIMESTAMP(0), false, false);

    /**
     * The parameter <code>weatherstation_db.stats_daily.windFactor</code>.
     */
    public static final Parameter<Double> WINDFACTOR = Internal.createParameter("windFactor", SQLDataType.FLOAT, false, false);

    /**
     * Create a new routine call instance
     */
    public StatsDaily() {
        super("stats_daily", WeatherstationDb.WEATHERSTATION_DB);

        addInParameter(STARTDATE);
        addInParameter(ENDDATE);
        addInParameter(WINDFACTOR);
    }

    /**
     * Set the <code>startDate</code> parameter IN value to the routine
     */
    public void setStartdate(Timestamp value) {
        setValue(STARTDATE, value);
    }

    /**
     * Set the <code>endDate</code> parameter IN value to the routine
     */
    public void setEnddate(Timestamp value) {
        setValue(ENDDATE, value);
    }

    /**
     * Set the <code>windFactor</code> parameter IN value to the routine
     */
    public void setWindfactor(Double value) {
        setValue(WINDFACTOR, value);
    }
}
