DROP TABLE IF EXISTS `aggregated`;
CREATE TABLE `aggregated`  (
  `min_ambient_temp` decimal(6, 2) NULL DEFAULT NULL,
  `min_ground_temp` decimal(6, 2) NULL DEFAULT NULL,
  `min_pressure` decimal(6, 2) NULL DEFAULT NULL,
  `min_humidity` decimal(6, 2) NULL DEFAULT NULL,
  `min_wind_average` decimal(6, 2) NULL DEFAULT NULL,
  `min_wind_speed` decimal(6, 2) NULL DEFAULT NULL,
  `min_wind_gust` decimal(6, 2) NULL DEFAULT NULL,
  `max_ambient_temp` decimal(6, 2) NULL DEFAULT NULL,
  `max_ground_temp` decimal(6, 2) NULL DEFAULT NULL,
  `max_pressure` decimal(6, 2) NULL DEFAULT NULL,
  `max_humidity` decimal(6, 2) NULL DEFAULT NULL,
  `max_wind_average` decimal(6, 2) NULL DEFAULT NULL,
  `max_wind_speed` decimal(6, 2) NULL DEFAULT NULL,
  `max_wind_gust` decimal(6, 2) NULL DEFAULT NULL,
  `avg_ambient_temp` decimal(6, 2) NULL DEFAULT NULL,
  `avg_ground_temp` decimal(6, 2) NULL DEFAULT NULL,
  `avg_pressure` decimal(6, 2) NULL DEFAULT NULL,
  `avg_humidity` decimal(6, 2) NULL DEFAULT NULL,
  `avg_wind_average` decimal(6, 2) NULL DEFAULT NULL,
  `avg_wind_speed` decimal(6, 2) NULL DEFAULT NULL,
  `avg_wind_gust` decimal(6, 2) NULL DEFAULT NULL,
  `std_ambient_temp` decimal(6, 2) NULL DEFAULT NULL,
  `std_ground_temp` decimal(6, 2) NULL DEFAULT NULL,
  `std_pressure` decimal(6, 2) NULL DEFAULT NULL,
  `std_humidity` decimal(6, 2) NULL DEFAULT NULL,
  `std_wind_average` decimal(6, 2) NULL DEFAULT NULL,
  `std_wind_speed` decimal(6, 2) NULL DEFAULT NULL,
  `std_wind_gust` decimal(6, 2) NULL DEFAULT NULL,
  `sum_rainfall` decimal(6, 2) NULL DEFAULT NULL,
  `date` date NOT NULL,
  PRIMARY KEY (`date`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_unicode_ci ROW_FORMAT = Dynamic;