/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables;


import java.math.BigDecimal;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.co.raubach.weatherstation.server.database.codegen.WeatherstationDb;
import uk.co.raubach.weatherstation.server.database.codegen.tables.records.AggregatedYearMonthRecord;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AggregatedYearMonth extends TableImpl<AggregatedYearMonthRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>weatherstation_db.aggregated_year_month</code>
     */
    public static final AggregatedYearMonth AGGREGATED_YEAR_MONTH = new AggregatedYearMonth();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AggregatedYearMonthRecord> getRecordType() {
        return AggregatedYearMonthRecord.class;
    }

    /**
     * The column
     * <code>weatherstation_db.aggregated_year_month.avg_ambient_temp</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> AVG_AMBIENT_TEMP = createField(DSL.name("avg_ambient_temp"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column
     * <code>weatherstation_db.aggregated_year_month.avg_ground_temp</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> AVG_GROUND_TEMP = createField(DSL.name("avg_ground_temp"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column
     * <code>weatherstation_db.aggregated_year_month.avg_loft_humidity</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> AVG_LOFT_HUMIDITY = createField(DSL.name("avg_loft_humidity"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column
     * <code>weatherstation_db.aggregated_year_month.avg_loft_temp</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> AVG_LOFT_TEMP = createField(DSL.name("avg_loft_temp"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.aggregated_year_month.avg_lux</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> AVG_LUX = createField(DSL.name("avg_lux"), SQLDataType.DECIMAL(8, 2), this, "");

    /**
     * The column
     * <code>weatherstation_db.aggregated_year_month.avg_pressure</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> AVG_PRESSURE = createField(DSL.name("avg_pressure"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column
     * <code>weatherstation_db.aggregated_year_month.avg_humidity</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> AVG_HUMIDITY = createField(DSL.name("avg_humidity"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column
     * <code>weatherstation_db.aggregated_year_month.avg_wind_speed</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> AVG_WIND_SPEED = createField(DSL.name("avg_wind_speed"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column
     * <code>weatherstation_db.aggregated_year_month.avg_wind_gust</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> AVG_WIND_GUST = createField(DSL.name("avg_wind_gust"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column
     * <code>weatherstation_db.aggregated_year_month.sum_rainfall</code>.
     */
    public final TableField<AggregatedYearMonthRecord, BigDecimal> SUM_RAINFALL = createField(DSL.name("sum_rainfall"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.aggregated_year_month.year</code>.
     */
    public final TableField<AggregatedYearMonthRecord, Short> YEAR = createField(DSL.name("year"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>weatherstation_db.aggregated_year_month.month</code>.
     */
    public final TableField<AggregatedYearMonthRecord, Short> MONTH = createField(DSL.name("month"), SQLDataType.SMALLINT.nullable(false), this, "");

    private AggregatedYearMonth(Name alias, Table<AggregatedYearMonthRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AggregatedYearMonth(Name alias, Table<AggregatedYearMonthRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>weatherstation_db.aggregated_year_month</code>
     * table reference
     */
    public AggregatedYearMonth(String alias) {
        this(DSL.name(alias), AGGREGATED_YEAR_MONTH);
    }

    /**
     * Create an aliased <code>weatherstation_db.aggregated_year_month</code>
     * table reference
     */
    public AggregatedYearMonth(Name alias) {
        this(alias, AGGREGATED_YEAR_MONTH);
    }

    /**
     * Create a <code>weatherstation_db.aggregated_year_month</code> table
     * reference
     */
    public AggregatedYearMonth() {
        this(DSL.name("aggregated_year_month"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : WeatherstationDb.WEATHERSTATION_DB;
    }

    @Override
    public UniqueKey<AggregatedYearMonthRecord> getPrimaryKey() {
        return Internal.createUniqueKey(AggregatedYearMonth.AGGREGATED_YEAR_MONTH, DSL.name("KEY_aggregated_year_month_PRIMARY"), new TableField[] { AggregatedYearMonth.AGGREGATED_YEAR_MONTH.YEAR, AggregatedYearMonth.AGGREGATED_YEAR_MONTH.MONTH }, true);
    }

    @Override
    public AggregatedYearMonth as(String alias) {
        return new AggregatedYearMonth(DSL.name(alias), this);
    }

    @Override
    public AggregatedYearMonth as(Name alias) {
        return new AggregatedYearMonth(alias, this);
    }

    @Override
    public AggregatedYearMonth as(Table<?> alias) {
        return new AggregatedYearMonth(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AggregatedYearMonth rename(String name) {
        return new AggregatedYearMonth(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AggregatedYearMonth rename(Name name) {
        return new AggregatedYearMonth(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AggregatedYearMonth rename(Table<?> name) {
        return new AggregatedYearMonth(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AggregatedYearMonth where(Condition condition) {
        return new AggregatedYearMonth(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AggregatedYearMonth where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AggregatedYearMonth where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AggregatedYearMonth where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AggregatedYearMonth where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AggregatedYearMonth where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AggregatedYearMonth where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AggregatedYearMonth where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AggregatedYearMonth whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AggregatedYearMonth whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
    // @formatter:on
}
