/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables;


import java.sql.Time;
import java.sql.Timestamp;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.co.raubach.weatherstation.server.database.codegen.WeatherstationDb;
import uk.co.raubach.weatherstation.server.database.codegen.tables.records.LuxClimatologyRecord;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LuxClimatology extends TableImpl<LuxClimatologyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>weatherstation_db.lux_climatology</code>
     */
    public static final LuxClimatology LUX_CLIMATOLOGY = new LuxClimatology();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LuxClimatologyRecord> getRecordType() {
        return LuxClimatologyRecord.class;
    }

    /**
     * The column <code>weatherstation_db.lux_climatology.month</code>.
     */
    public final TableField<LuxClimatologyRecord, Integer> MONTH = createField(DSL.name("month"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>weatherstation_db.lux_climatology.day</code>.
     */
    public final TableField<LuxClimatologyRecord, Integer> DAY = createField(DSL.name("day"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>weatherstation_db.lux_climatology.slot_time</code>.
     */
    public final TableField<LuxClimatologyRecord, Time> SLOT_TIME = createField(DSL.name("slot_time"), SQLDataType.TIME.nullable(false), this, "");

    /**
     * The column <code>weatherstation_db.lux_climatology.p95_lux</code>.
     */
    public final TableField<LuxClimatologyRecord, Double> P95_LUX = createField(DSL.name("p95_lux"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>weatherstation_db.lux_climatology.p95_lux_smooth</code>.
     */
    public final TableField<LuxClimatologyRecord, Double> P95_LUX_SMOOTH = createField(DSL.name("p95_lux_smooth"), SQLDataType.DOUBLE.nullable(false), this, "");

    /**
     * The column <code>weatherstation_db.lux_climatology.sample_count</code>.
     */
    public final TableField<LuxClimatologyRecord, Integer> SAMPLE_COUNT = createField(DSL.name("sample_count"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>weatherstation_db.lux_climatology.updated_at</code>.
     */
    public final TableField<LuxClimatologyRecord, Timestamp> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMP(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMP)), this, "");

    private LuxClimatology(Name alias, Table<LuxClimatologyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private LuxClimatology(Name alias, Table<LuxClimatologyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>weatherstation_db.lux_climatology</code> table
     * reference
     */
    public LuxClimatology(String alias) {
        this(DSL.name(alias), LUX_CLIMATOLOGY);
    }

    /**
     * Create an aliased <code>weatherstation_db.lux_climatology</code> table
     * reference
     */
    public LuxClimatology(Name alias) {
        this(alias, LUX_CLIMATOLOGY);
    }

    /**
     * Create a <code>weatherstation_db.lux_climatology</code> table reference
     */
    public LuxClimatology() {
        this(DSL.name("lux_climatology"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : WeatherstationDb.WEATHERSTATION_DB;
    }

    @Override
    public UniqueKey<LuxClimatologyRecord> getPrimaryKey() {
        return Internal.createUniqueKey(LuxClimatology.LUX_CLIMATOLOGY, DSL.name("KEY_lux_climatology_PRIMARY"), new TableField[] { LuxClimatology.LUX_CLIMATOLOGY.MONTH, LuxClimatology.LUX_CLIMATOLOGY.DAY, LuxClimatology.LUX_CLIMATOLOGY.SLOT_TIME }, true);
    }

    @Override
    public LuxClimatology as(String alias) {
        return new LuxClimatology(DSL.name(alias), this);
    }

    @Override
    public LuxClimatology as(Name alias) {
        return new LuxClimatology(alias, this);
    }

    @Override
    public LuxClimatology as(Table<?> alias) {
        return new LuxClimatology(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public LuxClimatology rename(String name) {
        return new LuxClimatology(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public LuxClimatology rename(Name name) {
        return new LuxClimatology(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public LuxClimatology rename(Table<?> name) {
        return new LuxClimatology(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LuxClimatology where(Condition condition) {
        return new LuxClimatology(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LuxClimatology where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LuxClimatology where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LuxClimatology where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LuxClimatology where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LuxClimatology where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LuxClimatology where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public LuxClimatology where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LuxClimatology whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public LuxClimatology whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
    // @formatter:on
}
