/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables;


import java.math.BigDecimal;
import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.co.raubach.weatherstation.server.database.codegen.WeatherstationDb;
import uk.co.raubach.weatherstation.server.database.codegen.tables.records.MeasurementsRecord;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Measurements extends TableImpl<MeasurementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>weatherstation_db.measurements</code>
     */
    public static final Measurements MEASUREMENTS = new Measurements();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MeasurementsRecord> getRecordType() {
        return MeasurementsRecord.class;
    }

    /**
     * The column <code>weatherstation_db.measurements.id</code>.
     */
    public final TableField<MeasurementsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>weatherstation_db.measurements.ambient_temp</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> AMBIENT_TEMP = createField(DSL.name("ambient_temp"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.measurements.ground_temp</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> GROUND_TEMP = createField(DSL.name("ground_temp"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.measurements.pressure</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> PRESSURE = createField(DSL.name("pressure"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.measurements.humidity</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> HUMIDITY = createField(DSL.name("humidity"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.measurements.wind_average</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> WIND_AVERAGE = createField(DSL.name("wind_average"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.measurements.wind_speed</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> WIND_SPEED = createField(DSL.name("wind_speed"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.measurements.wind_gust</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> WIND_GUST = createField(DSL.name("wind_gust"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.measurements.rainfall</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> RAINFALL = createField(DSL.name("rainfall"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.measurements.pi_temp</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> PI_TEMP = createField(DSL.name("pi_temp"), SQLDataType.DECIMAL(6, 2), this, "");

    /**
     * The column <code>weatherstation_db.measurements.lux</code>.
     */
    public final TableField<MeasurementsRecord, BigDecimal> LUX = createField(DSL.name("lux"), SQLDataType.DECIMAL(8, 2).defaultValue(DSL.inline("0.00", SQLDataType.DECIMAL)), this, "");

    /**
     * The column <code>weatherstation_db.measurements.uploaded_wu</code>.
     */
    public final TableField<MeasurementsRecord, Boolean> UPLOADED_WU = createField(DSL.name("uploaded_wu"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>weatherstation_db.measurements.created</code>.
     */
    public final TableField<MeasurementsRecord, Timestamp> CREATED = createField(DSL.name("created"), SQLDataType.TIMESTAMP(0).nullable(false).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.TIMESTAMP)), this, "");

    private Measurements(Name alias, Table<MeasurementsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Measurements(Name alias, Table<MeasurementsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>weatherstation_db.measurements</code> table
     * reference
     */
    public Measurements(String alias) {
        this(DSL.name(alias), MEASUREMENTS);
    }

    /**
     * Create an aliased <code>weatherstation_db.measurements</code> table
     * reference
     */
    public Measurements(Name alias) {
        this(alias, MEASUREMENTS);
    }

    /**
     * Create a <code>weatherstation_db.measurements</code> table reference
     */
    public Measurements() {
        this(DSL.name("measurements"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : WeatherstationDb.WEATHERSTATION_DB;
    }

    @Override
    public Identity<MeasurementsRecord, Long> getIdentity() {
        return (Identity<MeasurementsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<MeasurementsRecord> getPrimaryKey() {
        return Internal.createUniqueKey(Measurements.MEASUREMENTS, DSL.name("KEY_measurements_PRIMARY"), new TableField[] { Measurements.MEASUREMENTS.ID }, true);
    }

    @Override
    public Measurements as(String alias) {
        return new Measurements(DSL.name(alias), this);
    }

    @Override
    public Measurements as(Name alias) {
        return new Measurements(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Measurements rename(String name) {
        return new Measurements(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Measurements rename(Name name) {
        return new Measurements(name, null);
    }

    // -------------------------------------------------------------------------
    // Row13 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Boolean, Timestamp> fieldsRow() {
        return (Row13) super.fieldsRow();
    }
    // @formatter:on
}
