/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables;


import java.math.BigDecimal;
import java.sql.Date;
import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import uk.co.raubach.weatherstation.server.database.codegen.WeatherstationDb;
import uk.co.raubach.weatherstation.server.database.codegen.tables.records.ViewPeriodsRecord;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewPeriods extends TableImpl<ViewPeriodsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>weatherstation_db.view_periods</code>
     */
    public static final ViewPeriods VIEW_PERIODS = new ViewPeriods();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ViewPeriodsRecord> getRecordType() {
        return ViewPeriodsRecord.class;
    }

    /**
     * The column <code>weatherstation_db.view_periods.type</code>.
     */
    public final TableField<ViewPeriodsRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(18).nullable(false).defaultValue(DSL.inline("", SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>weatherstation_db.view_periods.start_date</code>.
     */
    public final TableField<ViewPeriodsRecord, Date> START_DATE = createField(DSL.name("start_date"), SQLDataType.DATE, this, "");

    /**
     * The column <code>weatherstation_db.view_periods.end_date</code>.
     */
    public final TableField<ViewPeriodsRecord, Date> END_DATE = createField(DSL.name("end_date"), SQLDataType.DATE, this, "");

    /**
     * The column <code>weatherstation_db.view_periods.consecutive_days</code>.
     */
    public final TableField<ViewPeriodsRecord, Long> CONSECUTIVE_DAYS = createField(DSL.name("consecutive_days"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.inline("0", SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>weatherstation_db.view_periods.total_rain_amount</code>.
     */
    public final TableField<ViewPeriodsRecord, BigDecimal> TOTAL_RAIN_AMOUNT = createField(DSL.name("total_rain_amount"), SQLDataType.DECIMAL(28, 2), this, "");

    private ViewPeriods(Name alias, Table<ViewPeriodsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private ViewPeriods(Name alias, Table<ViewPeriodsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.view("create view `view_periods` as with `wet_streaks` as (select `weather_station`.`aggregated`.`date` AS `date`,`weather_station`.`aggregated`.`sum_rainfall` AS `sum_rainfall`,(`weather_station`.`aggregated`.`date` - interval row_number() OVER (ORDER BY `weather_station`.`aggregated`.`date` )  day) AS `streak_id` from `weather_station`.`aggregated` where (`weather_station`.`aggregated`.`sum_rainfall` > 0)), `dry_streaks` as (select `weather_station`.`aggregated`.`date` AS `date`,`weather_station`.`aggregated`.`sum_rainfall` AS `sum_rainfall`,(`weather_station`.`aggregated`.`date` - interval row_number() OVER (ORDER BY `weather_station`.`aggregated`.`date` )  day) AS `streak_id` from `weather_station`.`aggregated` where (`weather_station`.`aggregated`.`sum_rainfall` = 0)) (select 'longest_wet_period' AS `type`,min(`wet_streaks`.`date`) AS `start_date`,max(`wet_streaks`.`date`) AS `end_date`,count(1) AS `consecutive_days`,sum(`wet_streaks`.`sum_rainfall`) AS `total_rain_amount` from `wet_streaks` group by `wet_streaks`.`streak_id` order by `consecutive_days` desc limit 1) union all (select 'longest_dry_period' AS `type`,min(`dry_streaks`.`date`) AS `start_date`,max(`dry_streaks`.`date`) AS `end_date`,count(1) AS `consecutive_days`,sum(`dry_streaks`.`sum_rainfall`) AS `total_rain_amount` from `dry_streaks` group by `dry_streaks`.`streak_id` order by `consecutive_days` desc limit 1)"), where);
    }

    /**
     * Create an aliased <code>weatherstation_db.view_periods</code> table
     * reference
     */
    public ViewPeriods(String alias) {
        this(DSL.name(alias), VIEW_PERIODS);
    }

    /**
     * Create an aliased <code>weatherstation_db.view_periods</code> table
     * reference
     */
    public ViewPeriods(Name alias) {
        this(alias, VIEW_PERIODS);
    }

    /**
     * Create a <code>weatherstation_db.view_periods</code> table reference
     */
    public ViewPeriods() {
        this(DSL.name("view_periods"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : WeatherstationDb.WEATHERSTATION_DB;
    }

    @Override
    public ViewPeriods as(String alias) {
        return new ViewPeriods(DSL.name(alias), this);
    }

    @Override
    public ViewPeriods as(Name alias) {
        return new ViewPeriods(alias, this);
    }

    @Override
    public ViewPeriods as(Table<?> alias) {
        return new ViewPeriods(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewPeriods rename(String name) {
        return new ViewPeriods(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewPeriods rename(Name name) {
        return new ViewPeriods(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public ViewPeriods rename(Table<?> name) {
        return new ViewPeriods(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewPeriods where(Condition condition) {
        return new ViewPeriods(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewPeriods where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewPeriods where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewPeriods where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewPeriods where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewPeriods where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewPeriods where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public ViewPeriods where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewPeriods whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public ViewPeriods whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
    // @formatter:on
}
