/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Aggregated implements Serializable {

    private static final long serialVersionUID = 1L;

    private BigDecimal minAmbientTemp;
    private BigDecimal minGroundTemp;
    private BigDecimal minPiTemp;
    private BigDecimal minLux;
    private BigDecimal minPressure;
    private BigDecimal minHumidity;
    private BigDecimal minWindAverage;
    private BigDecimal minWindSpeed;
    private BigDecimal minWindGust;
    private BigDecimal maxAmbientTemp;
    private BigDecimal maxGroundTemp;
    private BigDecimal maxPiTemp;
    private BigDecimal maxLux;
    private BigDecimal maxPressure;
    private BigDecimal maxHumidity;
    private BigDecimal maxWindAverage;
    private BigDecimal maxWindSpeed;
    private BigDecimal maxWindGust;
    private BigDecimal avgAmbientTemp;
    private BigDecimal avgGroundTemp;
    private BigDecimal avgPiTemp;
    private BigDecimal avgLux;
    private BigDecimal avgPressure;
    private BigDecimal avgHumidity;
    private BigDecimal avgWindAverage;
    private BigDecimal avgWindSpeed;
    private BigDecimal avgWindGust;
    private BigDecimal stdAmbientTemp;
    private BigDecimal stdGroundTemp;
    private BigDecimal stdPiTemp;
    private BigDecimal stdLux;
    private BigDecimal stdPressure;
    private BigDecimal stdHumidity;
    private BigDecimal stdWindAverage;
    private BigDecimal stdWindSpeed;
    private BigDecimal stdWindGust;
    private BigDecimal sumRainfall;
    private Date       date;

    public Aggregated() {}

    public Aggregated(Aggregated value) {
        this.minAmbientTemp = value.minAmbientTemp;
        this.minGroundTemp = value.minGroundTemp;
        this.minPiTemp = value.minPiTemp;
        this.minLux = value.minLux;
        this.minPressure = value.minPressure;
        this.minHumidity = value.minHumidity;
        this.minWindAverage = value.minWindAverage;
        this.minWindSpeed = value.minWindSpeed;
        this.minWindGust = value.minWindGust;
        this.maxAmbientTemp = value.maxAmbientTemp;
        this.maxGroundTemp = value.maxGroundTemp;
        this.maxPiTemp = value.maxPiTemp;
        this.maxLux = value.maxLux;
        this.maxPressure = value.maxPressure;
        this.maxHumidity = value.maxHumidity;
        this.maxWindAverage = value.maxWindAverage;
        this.maxWindSpeed = value.maxWindSpeed;
        this.maxWindGust = value.maxWindGust;
        this.avgAmbientTemp = value.avgAmbientTemp;
        this.avgGroundTemp = value.avgGroundTemp;
        this.avgPiTemp = value.avgPiTemp;
        this.avgLux = value.avgLux;
        this.avgPressure = value.avgPressure;
        this.avgHumidity = value.avgHumidity;
        this.avgWindAverage = value.avgWindAverage;
        this.avgWindSpeed = value.avgWindSpeed;
        this.avgWindGust = value.avgWindGust;
        this.stdAmbientTemp = value.stdAmbientTemp;
        this.stdGroundTemp = value.stdGroundTemp;
        this.stdPiTemp = value.stdPiTemp;
        this.stdLux = value.stdLux;
        this.stdPressure = value.stdPressure;
        this.stdHumidity = value.stdHumidity;
        this.stdWindAverage = value.stdWindAverage;
        this.stdWindSpeed = value.stdWindSpeed;
        this.stdWindGust = value.stdWindGust;
        this.sumRainfall = value.sumRainfall;
        this.date = value.date;
    }

    public Aggregated(
        BigDecimal minAmbientTemp,
        BigDecimal minGroundTemp,
        BigDecimal minPiTemp,
        BigDecimal minLux,
        BigDecimal minPressure,
        BigDecimal minHumidity,
        BigDecimal minWindAverage,
        BigDecimal minWindSpeed,
        BigDecimal minWindGust,
        BigDecimal maxAmbientTemp,
        BigDecimal maxGroundTemp,
        BigDecimal maxPiTemp,
        BigDecimal maxLux,
        BigDecimal maxPressure,
        BigDecimal maxHumidity,
        BigDecimal maxWindAverage,
        BigDecimal maxWindSpeed,
        BigDecimal maxWindGust,
        BigDecimal avgAmbientTemp,
        BigDecimal avgGroundTemp,
        BigDecimal avgPiTemp,
        BigDecimal avgLux,
        BigDecimal avgPressure,
        BigDecimal avgHumidity,
        BigDecimal avgWindAverage,
        BigDecimal avgWindSpeed,
        BigDecimal avgWindGust,
        BigDecimal stdAmbientTemp,
        BigDecimal stdGroundTemp,
        BigDecimal stdPiTemp,
        BigDecimal stdLux,
        BigDecimal stdPressure,
        BigDecimal stdHumidity,
        BigDecimal stdWindAverage,
        BigDecimal stdWindSpeed,
        BigDecimal stdWindGust,
        BigDecimal sumRainfall,
        Date       date
    ) {
        this.minAmbientTemp = minAmbientTemp;
        this.minGroundTemp = minGroundTemp;
        this.minPiTemp = minPiTemp;
        this.minLux = minLux;
        this.minPressure = minPressure;
        this.minHumidity = minHumidity;
        this.minWindAverage = minWindAverage;
        this.minWindSpeed = minWindSpeed;
        this.minWindGust = minWindGust;
        this.maxAmbientTemp = maxAmbientTemp;
        this.maxGroundTemp = maxGroundTemp;
        this.maxPiTemp = maxPiTemp;
        this.maxLux = maxLux;
        this.maxPressure = maxPressure;
        this.maxHumidity = maxHumidity;
        this.maxWindAverage = maxWindAverage;
        this.maxWindSpeed = maxWindSpeed;
        this.maxWindGust = maxWindGust;
        this.avgAmbientTemp = avgAmbientTemp;
        this.avgGroundTemp = avgGroundTemp;
        this.avgPiTemp = avgPiTemp;
        this.avgLux = avgLux;
        this.avgPressure = avgPressure;
        this.avgHumidity = avgHumidity;
        this.avgWindAverage = avgWindAverage;
        this.avgWindSpeed = avgWindSpeed;
        this.avgWindGust = avgWindGust;
        this.stdAmbientTemp = stdAmbientTemp;
        this.stdGroundTemp = stdGroundTemp;
        this.stdPiTemp = stdPiTemp;
        this.stdLux = stdLux;
        this.stdPressure = stdPressure;
        this.stdHumidity = stdHumidity;
        this.stdWindAverage = stdWindAverage;
        this.stdWindSpeed = stdWindSpeed;
        this.stdWindGust = stdWindGust;
        this.sumRainfall = sumRainfall;
        this.date = date;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.min_ambient_temp</code>.
     */
    public BigDecimal getMinAmbientTemp() {
        return this.minAmbientTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.min_ambient_temp</code>.
     */
    public void setMinAmbientTemp(BigDecimal minAmbientTemp) {
        this.minAmbientTemp = minAmbientTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.min_ground_temp</code>.
     */
    public BigDecimal getMinGroundTemp() {
        return this.minGroundTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.min_ground_temp</code>.
     */
    public void setMinGroundTemp(BigDecimal minGroundTemp) {
        this.minGroundTemp = minGroundTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.min_pi_temp</code>.
     */
    public BigDecimal getMinPiTemp() {
        return this.minPiTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.min_pi_temp</code>.
     */
    public void setMinPiTemp(BigDecimal minPiTemp) {
        this.minPiTemp = minPiTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.min_lux</code>.
     */
    public BigDecimal getMinLux() {
        return this.minLux;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.min_lux</code>.
     */
    public void setMinLux(BigDecimal minLux) {
        this.minLux = minLux;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.min_pressure</code>.
     */
    public BigDecimal getMinPressure() {
        return this.minPressure;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.min_pressure</code>.
     */
    public void setMinPressure(BigDecimal minPressure) {
        this.minPressure = minPressure;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.min_humidity</code>.
     */
    public BigDecimal getMinHumidity() {
        return this.minHumidity;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.min_humidity</code>.
     */
    public void setMinHumidity(BigDecimal minHumidity) {
        this.minHumidity = minHumidity;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.min_wind_average</code>.
     */
    public BigDecimal getMinWindAverage() {
        return this.minWindAverage;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.min_wind_average</code>.
     */
    public void setMinWindAverage(BigDecimal minWindAverage) {
        this.minWindAverage = minWindAverage;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.min_wind_speed</code>.
     */
    public BigDecimal getMinWindSpeed() {
        return this.minWindSpeed;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.min_wind_speed</code>.
     */
    public void setMinWindSpeed(BigDecimal minWindSpeed) {
        this.minWindSpeed = minWindSpeed;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.min_wind_gust</code>.
     */
    public BigDecimal getMinWindGust() {
        return this.minWindGust;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.min_wind_gust</code>.
     */
    public void setMinWindGust(BigDecimal minWindGust) {
        this.minWindGust = minWindGust;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.max_ambient_temp</code>.
     */
    public BigDecimal getMaxAmbientTemp() {
        return this.maxAmbientTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.max_ambient_temp</code>.
     */
    public void setMaxAmbientTemp(BigDecimal maxAmbientTemp) {
        this.maxAmbientTemp = maxAmbientTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.max_ground_temp</code>.
     */
    public BigDecimal getMaxGroundTemp() {
        return this.maxGroundTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.max_ground_temp</code>.
     */
    public void setMaxGroundTemp(BigDecimal maxGroundTemp) {
        this.maxGroundTemp = maxGroundTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.max_pi_temp</code>.
     */
    public BigDecimal getMaxPiTemp() {
        return this.maxPiTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.max_pi_temp</code>.
     */
    public void setMaxPiTemp(BigDecimal maxPiTemp) {
        this.maxPiTemp = maxPiTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.max_lux</code>.
     */
    public BigDecimal getMaxLux() {
        return this.maxLux;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.max_lux</code>.
     */
    public void setMaxLux(BigDecimal maxLux) {
        this.maxLux = maxLux;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.max_pressure</code>.
     */
    public BigDecimal getMaxPressure() {
        return this.maxPressure;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.max_pressure</code>.
     */
    public void setMaxPressure(BigDecimal maxPressure) {
        this.maxPressure = maxPressure;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.max_humidity</code>.
     */
    public BigDecimal getMaxHumidity() {
        return this.maxHumidity;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.max_humidity</code>.
     */
    public void setMaxHumidity(BigDecimal maxHumidity) {
        this.maxHumidity = maxHumidity;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.max_wind_average</code>.
     */
    public BigDecimal getMaxWindAverage() {
        return this.maxWindAverage;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.max_wind_average</code>.
     */
    public void setMaxWindAverage(BigDecimal maxWindAverage) {
        this.maxWindAverage = maxWindAverage;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.max_wind_speed</code>.
     */
    public BigDecimal getMaxWindSpeed() {
        return this.maxWindSpeed;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.max_wind_speed</code>.
     */
    public void setMaxWindSpeed(BigDecimal maxWindSpeed) {
        this.maxWindSpeed = maxWindSpeed;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.max_wind_gust</code>.
     */
    public BigDecimal getMaxWindGust() {
        return this.maxWindGust;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.max_wind_gust</code>.
     */
    public void setMaxWindGust(BigDecimal maxWindGust) {
        this.maxWindGust = maxWindGust;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.avg_ambient_temp</code>.
     */
    public BigDecimal getAvgAmbientTemp() {
        return this.avgAmbientTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.avg_ambient_temp</code>.
     */
    public void setAvgAmbientTemp(BigDecimal avgAmbientTemp) {
        this.avgAmbientTemp = avgAmbientTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.avg_ground_temp</code>.
     */
    public BigDecimal getAvgGroundTemp() {
        return this.avgGroundTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.avg_ground_temp</code>.
     */
    public void setAvgGroundTemp(BigDecimal avgGroundTemp) {
        this.avgGroundTemp = avgGroundTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.avg_pi_temp</code>.
     */
    public BigDecimal getAvgPiTemp() {
        return this.avgPiTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.avg_pi_temp</code>.
     */
    public void setAvgPiTemp(BigDecimal avgPiTemp) {
        this.avgPiTemp = avgPiTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.avg_lux</code>.
     */
    public BigDecimal getAvgLux() {
        return this.avgLux;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.avg_lux</code>.
     */
    public void setAvgLux(BigDecimal avgLux) {
        this.avgLux = avgLux;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.avg_pressure</code>.
     */
    public BigDecimal getAvgPressure() {
        return this.avgPressure;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.avg_pressure</code>.
     */
    public void setAvgPressure(BigDecimal avgPressure) {
        this.avgPressure = avgPressure;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.avg_humidity</code>.
     */
    public BigDecimal getAvgHumidity() {
        return this.avgHumidity;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.avg_humidity</code>.
     */
    public void setAvgHumidity(BigDecimal avgHumidity) {
        this.avgHumidity = avgHumidity;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.avg_wind_average</code>.
     */
    public BigDecimal getAvgWindAverage() {
        return this.avgWindAverage;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.avg_wind_average</code>.
     */
    public void setAvgWindAverage(BigDecimal avgWindAverage) {
        this.avgWindAverage = avgWindAverage;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.avg_wind_speed</code>.
     */
    public BigDecimal getAvgWindSpeed() {
        return this.avgWindSpeed;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.avg_wind_speed</code>.
     */
    public void setAvgWindSpeed(BigDecimal avgWindSpeed) {
        this.avgWindSpeed = avgWindSpeed;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.avg_wind_gust</code>.
     */
    public BigDecimal getAvgWindGust() {
        return this.avgWindGust;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.avg_wind_gust</code>.
     */
    public void setAvgWindGust(BigDecimal avgWindGust) {
        this.avgWindGust = avgWindGust;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.std_ambient_temp</code>.
     */
    public BigDecimal getStdAmbientTemp() {
        return this.stdAmbientTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.std_ambient_temp</code>.
     */
    public void setStdAmbientTemp(BigDecimal stdAmbientTemp) {
        this.stdAmbientTemp = stdAmbientTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.std_ground_temp</code>.
     */
    public BigDecimal getStdGroundTemp() {
        return this.stdGroundTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.std_ground_temp</code>.
     */
    public void setStdGroundTemp(BigDecimal stdGroundTemp) {
        this.stdGroundTemp = stdGroundTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.std_pi_temp</code>.
     */
    public BigDecimal getStdPiTemp() {
        return this.stdPiTemp;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.std_pi_temp</code>.
     */
    public void setStdPiTemp(BigDecimal stdPiTemp) {
        this.stdPiTemp = stdPiTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.std_lux</code>.
     */
    public BigDecimal getStdLux() {
        return this.stdLux;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.std_lux</code>.
     */
    public void setStdLux(BigDecimal stdLux) {
        this.stdLux = stdLux;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.std_pressure</code>.
     */
    public BigDecimal getStdPressure() {
        return this.stdPressure;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.std_pressure</code>.
     */
    public void setStdPressure(BigDecimal stdPressure) {
        this.stdPressure = stdPressure;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.std_humidity</code>.
     */
    public BigDecimal getStdHumidity() {
        return this.stdHumidity;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.std_humidity</code>.
     */
    public void setStdHumidity(BigDecimal stdHumidity) {
        this.stdHumidity = stdHumidity;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.std_wind_average</code>.
     */
    public BigDecimal getStdWindAverage() {
        return this.stdWindAverage;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.std_wind_average</code>.
     */
    public void setStdWindAverage(BigDecimal stdWindAverage) {
        this.stdWindAverage = stdWindAverage;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.std_wind_speed</code>.
     */
    public BigDecimal getStdWindSpeed() {
        return this.stdWindSpeed;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.std_wind_speed</code>.
     */
    public void setStdWindSpeed(BigDecimal stdWindSpeed) {
        this.stdWindSpeed = stdWindSpeed;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.std_wind_gust</code>.
     */
    public BigDecimal getStdWindGust() {
        return this.stdWindGust;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.std_wind_gust</code>.
     */
    public void setStdWindGust(BigDecimal stdWindGust) {
        this.stdWindGust = stdWindGust;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.sum_rainfall</code>.
     */
    public BigDecimal getSumRainfall() {
        return this.sumRainfall;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.sum_rainfall</code>.
     */
    public void setSumRainfall(BigDecimal sumRainfall) {
        this.sumRainfall = sumRainfall;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated.date</code>.
     */
    public Date getDate() {
        return this.date;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated.date</code>.
     */
    public void setDate(Date date) {
        this.date = date;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Aggregated (");

        sb.append(minAmbientTemp);
        sb.append(", ").append(minGroundTemp);
        sb.append(", ").append(minPiTemp);
        sb.append(", ").append(minLux);
        sb.append(", ").append(minPressure);
        sb.append(", ").append(minHumidity);
        sb.append(", ").append(minWindAverage);
        sb.append(", ").append(minWindSpeed);
        sb.append(", ").append(minWindGust);
        sb.append(", ").append(maxAmbientTemp);
        sb.append(", ").append(maxGroundTemp);
        sb.append(", ").append(maxPiTemp);
        sb.append(", ").append(maxLux);
        sb.append(", ").append(maxPressure);
        sb.append(", ").append(maxHumidity);
        sb.append(", ").append(maxWindAverage);
        sb.append(", ").append(maxWindSpeed);
        sb.append(", ").append(maxWindGust);
        sb.append(", ").append(avgAmbientTemp);
        sb.append(", ").append(avgGroundTemp);
        sb.append(", ").append(avgPiTemp);
        sb.append(", ").append(avgLux);
        sb.append(", ").append(avgPressure);
        sb.append(", ").append(avgHumidity);
        sb.append(", ").append(avgWindAverage);
        sb.append(", ").append(avgWindSpeed);
        sb.append(", ").append(avgWindGust);
        sb.append(", ").append(stdAmbientTemp);
        sb.append(", ").append(stdGroundTemp);
        sb.append(", ").append(stdPiTemp);
        sb.append(", ").append(stdLux);
        sb.append(", ").append(stdPressure);
        sb.append(", ").append(stdHumidity);
        sb.append(", ").append(stdWindAverage);
        sb.append(", ").append(stdWindSpeed);
        sb.append(", ").append(stdWindGust);
        sb.append(", ").append(sumRainfall);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
