/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Aggregated implements Serializable {

    private static final long serialVersionUID = 1689154967;

    private BigDecimal minAmbientTemp;
    private BigDecimal minGroundTemp;
    private BigDecimal minPiTemp;
    private BigDecimal minPressure;
    private BigDecimal minHumidity;
    private BigDecimal minWindAverage;
    private BigDecimal minWindSpeed;
    private BigDecimal minWindGust;
    private BigDecimal maxAmbientTemp;
    private BigDecimal maxGroundTemp;
    private BigDecimal maxPiTemp;
    private BigDecimal maxPressure;
    private BigDecimal maxHumidity;
    private BigDecimal maxWindAverage;
    private BigDecimal maxWindSpeed;
    private BigDecimal maxWindGust;
    private BigDecimal avgAmbientTemp;
    private BigDecimal avgGroundTemp;
    private BigDecimal avgPiTemp;
    private BigDecimal avgPressure;
    private BigDecimal avgHumidity;
    private BigDecimal avgWindAverage;
    private BigDecimal avgWindSpeed;
    private BigDecimal avgWindGust;
    private BigDecimal stdAmbientTemp;
    private BigDecimal stdGroundTemp;
    private BigDecimal stdPiTemp;
    private BigDecimal stdPressure;
    private BigDecimal stdHumidity;
    private BigDecimal stdWindAverage;
    private BigDecimal stdWindSpeed;
    private BigDecimal stdWindGust;
    private BigDecimal sumRainfall;
    private Date       date;

    public Aggregated() {}

    public Aggregated(Aggregated value) {
        this.minAmbientTemp = value.minAmbientTemp;
        this.minGroundTemp = value.minGroundTemp;
        this.minPiTemp = value.minPiTemp;
        this.minPressure = value.minPressure;
        this.minHumidity = value.minHumidity;
        this.minWindAverage = value.minWindAverage;
        this.minWindSpeed = value.minWindSpeed;
        this.minWindGust = value.minWindGust;
        this.maxAmbientTemp = value.maxAmbientTemp;
        this.maxGroundTemp = value.maxGroundTemp;
        this.maxPiTemp = value.maxPiTemp;
        this.maxPressure = value.maxPressure;
        this.maxHumidity = value.maxHumidity;
        this.maxWindAverage = value.maxWindAverage;
        this.maxWindSpeed = value.maxWindSpeed;
        this.maxWindGust = value.maxWindGust;
        this.avgAmbientTemp = value.avgAmbientTemp;
        this.avgGroundTemp = value.avgGroundTemp;
        this.avgPiTemp = value.avgPiTemp;
        this.avgPressure = value.avgPressure;
        this.avgHumidity = value.avgHumidity;
        this.avgWindAverage = value.avgWindAverage;
        this.avgWindSpeed = value.avgWindSpeed;
        this.avgWindGust = value.avgWindGust;
        this.stdAmbientTemp = value.stdAmbientTemp;
        this.stdGroundTemp = value.stdGroundTemp;
        this.stdPiTemp = value.stdPiTemp;
        this.stdPressure = value.stdPressure;
        this.stdHumidity = value.stdHumidity;
        this.stdWindAverage = value.stdWindAverage;
        this.stdWindSpeed = value.stdWindSpeed;
        this.stdWindGust = value.stdWindGust;
        this.sumRainfall = value.sumRainfall;
        this.date = value.date;
    }

    public Aggregated(
        BigDecimal minAmbientTemp,
        BigDecimal minGroundTemp,
        BigDecimal minPiTemp,
        BigDecimal minPressure,
        BigDecimal minHumidity,
        BigDecimal minWindAverage,
        BigDecimal minWindSpeed,
        BigDecimal minWindGust,
        BigDecimal maxAmbientTemp,
        BigDecimal maxGroundTemp,
        BigDecimal maxPiTemp,
        BigDecimal maxPressure,
        BigDecimal maxHumidity,
        BigDecimal maxWindAverage,
        BigDecimal maxWindSpeed,
        BigDecimal maxWindGust,
        BigDecimal avgAmbientTemp,
        BigDecimal avgGroundTemp,
        BigDecimal avgPiTemp,
        BigDecimal avgPressure,
        BigDecimal avgHumidity,
        BigDecimal avgWindAverage,
        BigDecimal avgWindSpeed,
        BigDecimal avgWindGust,
        BigDecimal stdAmbientTemp,
        BigDecimal stdGroundTemp,
        BigDecimal stdPiTemp,
        BigDecimal stdPressure,
        BigDecimal stdHumidity,
        BigDecimal stdWindAverage,
        BigDecimal stdWindSpeed,
        BigDecimal stdWindGust,
        BigDecimal sumRainfall,
        Date       date
    ) {
        this.minAmbientTemp = minAmbientTemp;
        this.minGroundTemp = minGroundTemp;
        this.minPiTemp = minPiTemp;
        this.minPressure = minPressure;
        this.minHumidity = minHumidity;
        this.minWindAverage = minWindAverage;
        this.minWindSpeed = minWindSpeed;
        this.minWindGust = minWindGust;
        this.maxAmbientTemp = maxAmbientTemp;
        this.maxGroundTemp = maxGroundTemp;
        this.maxPiTemp = maxPiTemp;
        this.maxPressure = maxPressure;
        this.maxHumidity = maxHumidity;
        this.maxWindAverage = maxWindAverage;
        this.maxWindSpeed = maxWindSpeed;
        this.maxWindGust = maxWindGust;
        this.avgAmbientTemp = avgAmbientTemp;
        this.avgGroundTemp = avgGroundTemp;
        this.avgPiTemp = avgPiTemp;
        this.avgPressure = avgPressure;
        this.avgHumidity = avgHumidity;
        this.avgWindAverage = avgWindAverage;
        this.avgWindSpeed = avgWindSpeed;
        this.avgWindGust = avgWindGust;
        this.stdAmbientTemp = stdAmbientTemp;
        this.stdGroundTemp = stdGroundTemp;
        this.stdPiTemp = stdPiTemp;
        this.stdPressure = stdPressure;
        this.stdHumidity = stdHumidity;
        this.stdWindAverage = stdWindAverage;
        this.stdWindSpeed = stdWindSpeed;
        this.stdWindGust = stdWindGust;
        this.sumRainfall = sumRainfall;
        this.date = date;
    }

    public BigDecimal getMinAmbientTemp() {
        return this.minAmbientTemp;
    }

    public void setMinAmbientTemp(BigDecimal minAmbientTemp) {
        this.minAmbientTemp = minAmbientTemp;
    }

    public BigDecimal getMinGroundTemp() {
        return this.minGroundTemp;
    }

    public void setMinGroundTemp(BigDecimal minGroundTemp) {
        this.minGroundTemp = minGroundTemp;
    }

    public BigDecimal getMinPiTemp() {
        return this.minPiTemp;
    }

    public void setMinPiTemp(BigDecimal minPiTemp) {
        this.minPiTemp = minPiTemp;
    }

    public BigDecimal getMinPressure() {
        return this.minPressure;
    }

    public void setMinPressure(BigDecimal minPressure) {
        this.minPressure = minPressure;
    }

    public BigDecimal getMinHumidity() {
        return this.minHumidity;
    }

    public void setMinHumidity(BigDecimal minHumidity) {
        this.minHumidity = minHumidity;
    }

    public BigDecimal getMinWindAverage() {
        return this.minWindAverage;
    }

    public void setMinWindAverage(BigDecimal minWindAverage) {
        this.minWindAverage = minWindAverage;
    }

    public BigDecimal getMinWindSpeed() {
        return this.minWindSpeed;
    }

    public void setMinWindSpeed(BigDecimal minWindSpeed) {
        this.minWindSpeed = minWindSpeed;
    }

    public BigDecimal getMinWindGust() {
        return this.minWindGust;
    }

    public void setMinWindGust(BigDecimal minWindGust) {
        this.minWindGust = minWindGust;
    }

    public BigDecimal getMaxAmbientTemp() {
        return this.maxAmbientTemp;
    }

    public void setMaxAmbientTemp(BigDecimal maxAmbientTemp) {
        this.maxAmbientTemp = maxAmbientTemp;
    }

    public BigDecimal getMaxGroundTemp() {
        return this.maxGroundTemp;
    }

    public void setMaxGroundTemp(BigDecimal maxGroundTemp) {
        this.maxGroundTemp = maxGroundTemp;
    }

    public BigDecimal getMaxPiTemp() {
        return this.maxPiTemp;
    }

    public void setMaxPiTemp(BigDecimal maxPiTemp) {
        this.maxPiTemp = maxPiTemp;
    }

    public BigDecimal getMaxPressure() {
        return this.maxPressure;
    }

    public void setMaxPressure(BigDecimal maxPressure) {
        this.maxPressure = maxPressure;
    }

    public BigDecimal getMaxHumidity() {
        return this.maxHumidity;
    }

    public void setMaxHumidity(BigDecimal maxHumidity) {
        this.maxHumidity = maxHumidity;
    }

    public BigDecimal getMaxWindAverage() {
        return this.maxWindAverage;
    }

    public void setMaxWindAverage(BigDecimal maxWindAverage) {
        this.maxWindAverage = maxWindAverage;
    }

    public BigDecimal getMaxWindSpeed() {
        return this.maxWindSpeed;
    }

    public void setMaxWindSpeed(BigDecimal maxWindSpeed) {
        this.maxWindSpeed = maxWindSpeed;
    }

    public BigDecimal getMaxWindGust() {
        return this.maxWindGust;
    }

    public void setMaxWindGust(BigDecimal maxWindGust) {
        this.maxWindGust = maxWindGust;
    }

    public BigDecimal getAvgAmbientTemp() {
        return this.avgAmbientTemp;
    }

    public void setAvgAmbientTemp(BigDecimal avgAmbientTemp) {
        this.avgAmbientTemp = avgAmbientTemp;
    }

    public BigDecimal getAvgGroundTemp() {
        return this.avgGroundTemp;
    }

    public void setAvgGroundTemp(BigDecimal avgGroundTemp) {
        this.avgGroundTemp = avgGroundTemp;
    }

    public BigDecimal getAvgPiTemp() {
        return this.avgPiTemp;
    }

    public void setAvgPiTemp(BigDecimal avgPiTemp) {
        this.avgPiTemp = avgPiTemp;
    }

    public BigDecimal getAvgPressure() {
        return this.avgPressure;
    }

    public void setAvgPressure(BigDecimal avgPressure) {
        this.avgPressure = avgPressure;
    }

    public BigDecimal getAvgHumidity() {
        return this.avgHumidity;
    }

    public void setAvgHumidity(BigDecimal avgHumidity) {
        this.avgHumidity = avgHumidity;
    }

    public BigDecimal getAvgWindAverage() {
        return this.avgWindAverage;
    }

    public void setAvgWindAverage(BigDecimal avgWindAverage) {
        this.avgWindAverage = avgWindAverage;
    }

    public BigDecimal getAvgWindSpeed() {
        return this.avgWindSpeed;
    }

    public void setAvgWindSpeed(BigDecimal avgWindSpeed) {
        this.avgWindSpeed = avgWindSpeed;
    }

    public BigDecimal getAvgWindGust() {
        return this.avgWindGust;
    }

    public void setAvgWindGust(BigDecimal avgWindGust) {
        this.avgWindGust = avgWindGust;
    }

    public BigDecimal getStdAmbientTemp() {
        return this.stdAmbientTemp;
    }

    public void setStdAmbientTemp(BigDecimal stdAmbientTemp) {
        this.stdAmbientTemp = stdAmbientTemp;
    }

    public BigDecimal getStdGroundTemp() {
        return this.stdGroundTemp;
    }

    public void setStdGroundTemp(BigDecimal stdGroundTemp) {
        this.stdGroundTemp = stdGroundTemp;
    }

    public BigDecimal getStdPiTemp() {
        return this.stdPiTemp;
    }

    public void setStdPiTemp(BigDecimal stdPiTemp) {
        this.stdPiTemp = stdPiTemp;
    }

    public BigDecimal getStdPressure() {
        return this.stdPressure;
    }

    public void setStdPressure(BigDecimal stdPressure) {
        this.stdPressure = stdPressure;
    }

    public BigDecimal getStdHumidity() {
        return this.stdHumidity;
    }

    public void setStdHumidity(BigDecimal stdHumidity) {
        this.stdHumidity = stdHumidity;
    }

    public BigDecimal getStdWindAverage() {
        return this.stdWindAverage;
    }

    public void setStdWindAverage(BigDecimal stdWindAverage) {
        this.stdWindAverage = stdWindAverage;
    }

    public BigDecimal getStdWindSpeed() {
        return this.stdWindSpeed;
    }

    public void setStdWindSpeed(BigDecimal stdWindSpeed) {
        this.stdWindSpeed = stdWindSpeed;
    }

    public BigDecimal getStdWindGust() {
        return this.stdWindGust;
    }

    public void setStdWindGust(BigDecimal stdWindGust) {
        this.stdWindGust = stdWindGust;
    }

    public BigDecimal getSumRainfall() {
        return this.sumRainfall;
    }

    public void setSumRainfall(BigDecimal sumRainfall) {
        this.sumRainfall = sumRainfall;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Aggregated (");

        sb.append(minAmbientTemp);
        sb.append(", ").append(minGroundTemp);
        sb.append(", ").append(minPiTemp);
        sb.append(", ").append(minPressure);
        sb.append(", ").append(minHumidity);
        sb.append(", ").append(minWindAverage);
        sb.append(", ").append(minWindSpeed);
        sb.append(", ").append(minWindGust);
        sb.append(", ").append(maxAmbientTemp);
        sb.append(", ").append(maxGroundTemp);
        sb.append(", ").append(maxPiTemp);
        sb.append(", ").append(maxPressure);
        sb.append(", ").append(maxHumidity);
        sb.append(", ").append(maxWindAverage);
        sb.append(", ").append(maxWindSpeed);
        sb.append(", ").append(maxWindGust);
        sb.append(", ").append(avgAmbientTemp);
        sb.append(", ").append(avgGroundTemp);
        sb.append(", ").append(avgPiTemp);
        sb.append(", ").append(avgPressure);
        sb.append(", ").append(avgHumidity);
        sb.append(", ").append(avgWindAverage);
        sb.append(", ").append(avgWindSpeed);
        sb.append(", ").append(avgWindGust);
        sb.append(", ").append(stdAmbientTemp);
        sb.append(", ").append(stdGroundTemp);
        sb.append(", ").append(stdPiTemp);
        sb.append(", ").append(stdPressure);
        sb.append(", ").append(stdHumidity);
        sb.append(", ").append(stdWindAverage);
        sb.append(", ").append(stdWindSpeed);
        sb.append(", ").append(stdWindGust);
        sb.append(", ").append(sumRainfall);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
