/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AggregatedYearMonth implements Serializable {

    private static final long serialVersionUID = 1L;

    private BigDecimal avgAmbientTemp;
    private BigDecimal avgGroundTemp;
    private BigDecimal avgLoftHumidity;
    private BigDecimal avgLoftTemp;
    private BigDecimal avgLux;
    private BigDecimal avgPressure;
    private BigDecimal avgHumidity;
    private BigDecimal avgWindSpeed;
    private BigDecimal avgWindGust;
    private BigDecimal sumRainfall;
    private Short year;
    private Short month;

    public AggregatedYearMonth() {}

    public AggregatedYearMonth(AggregatedYearMonth value) {
        this.avgAmbientTemp = value.avgAmbientTemp;
        this.avgGroundTemp = value.avgGroundTemp;
        this.avgLoftHumidity = value.avgLoftHumidity;
        this.avgLoftTemp = value.avgLoftTemp;
        this.avgLux = value.avgLux;
        this.avgPressure = value.avgPressure;
        this.avgHumidity = value.avgHumidity;
        this.avgWindSpeed = value.avgWindSpeed;
        this.avgWindGust = value.avgWindGust;
        this.sumRainfall = value.sumRainfall;
        this.year = value.year;
        this.month = value.month;
    }

    public AggregatedYearMonth(
        BigDecimal avgAmbientTemp,
        BigDecimal avgGroundTemp,
        BigDecimal avgLoftHumidity,
        BigDecimal avgLoftTemp,
        BigDecimal avgLux,
        BigDecimal avgPressure,
        BigDecimal avgHumidity,
        BigDecimal avgWindSpeed,
        BigDecimal avgWindGust,
        BigDecimal sumRainfall,
        Short year,
        Short month
    ) {
        this.avgAmbientTemp = avgAmbientTemp;
        this.avgGroundTemp = avgGroundTemp;
        this.avgLoftHumidity = avgLoftHumidity;
        this.avgLoftTemp = avgLoftTemp;
        this.avgLux = avgLux;
        this.avgPressure = avgPressure;
        this.avgHumidity = avgHumidity;
        this.avgWindSpeed = avgWindSpeed;
        this.avgWindGust = avgWindGust;
        this.sumRainfall = sumRainfall;
        this.year = year;
        this.month = month;
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_ambient_temp</code>.
     */
    public BigDecimal getAvgAmbientTemp() {
        return this.avgAmbientTemp;
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_ambient_temp</code>.
     */
    public void setAvgAmbientTemp(BigDecimal avgAmbientTemp) {
        this.avgAmbientTemp = avgAmbientTemp;
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_ground_temp</code>.
     */
    public BigDecimal getAvgGroundTemp() {
        return this.avgGroundTemp;
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_ground_temp</code>.
     */
    public void setAvgGroundTemp(BigDecimal avgGroundTemp) {
        this.avgGroundTemp = avgGroundTemp;
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_loft_humidity</code>.
     */
    public BigDecimal getAvgLoftHumidity() {
        return this.avgLoftHumidity;
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_loft_humidity</code>.
     */
    public void setAvgLoftHumidity(BigDecimal avgLoftHumidity) {
        this.avgLoftHumidity = avgLoftHumidity;
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_loft_temp</code>.
     */
    public BigDecimal getAvgLoftTemp() {
        return this.avgLoftTemp;
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_loft_temp</code>.
     */
    public void setAvgLoftTemp(BigDecimal avgLoftTemp) {
        this.avgLoftTemp = avgLoftTemp;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated_year_month.avg_lux</code>.
     */
    public BigDecimal getAvgLux() {
        return this.avgLux;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated_year_month.avg_lux</code>.
     */
    public void setAvgLux(BigDecimal avgLux) {
        this.avgLux = avgLux;
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_pressure</code>.
     */
    public BigDecimal getAvgPressure() {
        return this.avgPressure;
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_pressure</code>.
     */
    public void setAvgPressure(BigDecimal avgPressure) {
        this.avgPressure = avgPressure;
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_humidity</code>.
     */
    public BigDecimal getAvgHumidity() {
        return this.avgHumidity;
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_humidity</code>.
     */
    public void setAvgHumidity(BigDecimal avgHumidity) {
        this.avgHumidity = avgHumidity;
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_speed</code>.
     */
    public BigDecimal getAvgWindSpeed() {
        return this.avgWindSpeed;
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_speed</code>.
     */
    public void setAvgWindSpeed(BigDecimal avgWindSpeed) {
        this.avgWindSpeed = avgWindSpeed;
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_gust</code>.
     */
    public BigDecimal getAvgWindGust() {
        return this.avgWindGust;
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_gust</code>.
     */
    public void setAvgWindGust(BigDecimal avgWindGust) {
        this.avgWindGust = avgWindGust;
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.sum_rainfall</code>.
     */
    public BigDecimal getSumRainfall() {
        return this.sumRainfall;
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.sum_rainfall</code>.
     */
    public void setSumRainfall(BigDecimal sumRainfall) {
        this.sumRainfall = sumRainfall;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated_year_month.year</code>.
     */
    public Short getYear() {
        return this.year;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated_year_month.year</code>.
     */
    public void setYear(Short year) {
        this.year = year;
    }

    /**
     * Getter for <code>weatherstation_db.aggregated_year_month.month</code>.
     */
    public Short getMonth() {
        return this.month;
    }

    /**
     * Setter for <code>weatherstation_db.aggregated_year_month.month</code>.
     */
    public void setMonth(Short month) {
        this.month = month;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final AggregatedYearMonth other = (AggregatedYearMonth) obj;
        if (this.avgAmbientTemp == null) {
            if (other.avgAmbientTemp != null)
                return false;
        }
        else if (!this.avgAmbientTemp.equals(other.avgAmbientTemp))
            return false;
        if (this.avgGroundTemp == null) {
            if (other.avgGroundTemp != null)
                return false;
        }
        else if (!this.avgGroundTemp.equals(other.avgGroundTemp))
            return false;
        if (this.avgLoftHumidity == null) {
            if (other.avgLoftHumidity != null)
                return false;
        }
        else if (!this.avgLoftHumidity.equals(other.avgLoftHumidity))
            return false;
        if (this.avgLoftTemp == null) {
            if (other.avgLoftTemp != null)
                return false;
        }
        else if (!this.avgLoftTemp.equals(other.avgLoftTemp))
            return false;
        if (this.avgLux == null) {
            if (other.avgLux != null)
                return false;
        }
        else if (!this.avgLux.equals(other.avgLux))
            return false;
        if (this.avgPressure == null) {
            if (other.avgPressure != null)
                return false;
        }
        else if (!this.avgPressure.equals(other.avgPressure))
            return false;
        if (this.avgHumidity == null) {
            if (other.avgHumidity != null)
                return false;
        }
        else if (!this.avgHumidity.equals(other.avgHumidity))
            return false;
        if (this.avgWindSpeed == null) {
            if (other.avgWindSpeed != null)
                return false;
        }
        else if (!this.avgWindSpeed.equals(other.avgWindSpeed))
            return false;
        if (this.avgWindGust == null) {
            if (other.avgWindGust != null)
                return false;
        }
        else if (!this.avgWindGust.equals(other.avgWindGust))
            return false;
        if (this.sumRainfall == null) {
            if (other.sumRainfall != null)
                return false;
        }
        else if (!this.sumRainfall.equals(other.sumRainfall))
            return false;
        if (this.year == null) {
            if (other.year != null)
                return false;
        }
        else if (!this.year.equals(other.year))
            return false;
        if (this.month == null) {
            if (other.month != null)
                return false;
        }
        else if (!this.month.equals(other.month))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.avgAmbientTemp == null) ? 0 : this.avgAmbientTemp.hashCode());
        result = prime * result + ((this.avgGroundTemp == null) ? 0 : this.avgGroundTemp.hashCode());
        result = prime * result + ((this.avgLoftHumidity == null) ? 0 : this.avgLoftHumidity.hashCode());
        result = prime * result + ((this.avgLoftTemp == null) ? 0 : this.avgLoftTemp.hashCode());
        result = prime * result + ((this.avgLux == null) ? 0 : this.avgLux.hashCode());
        result = prime * result + ((this.avgPressure == null) ? 0 : this.avgPressure.hashCode());
        result = prime * result + ((this.avgHumidity == null) ? 0 : this.avgHumidity.hashCode());
        result = prime * result + ((this.avgWindSpeed == null) ? 0 : this.avgWindSpeed.hashCode());
        result = prime * result + ((this.avgWindGust == null) ? 0 : this.avgWindGust.hashCode());
        result = prime * result + ((this.sumRainfall == null) ? 0 : this.sumRainfall.hashCode());
        result = prime * result + ((this.year == null) ? 0 : this.year.hashCode());
        result = prime * result + ((this.month == null) ? 0 : this.month.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("AggregatedYearMonth (");

        sb.append(avgAmbientTemp);
        sb.append(", ").append(avgGroundTemp);
        sb.append(", ").append(avgLoftHumidity);
        sb.append(", ").append(avgLoftTemp);
        sb.append(", ").append(avgLux);
        sb.append(", ").append(avgPressure);
        sb.append(", ").append(avgHumidity);
        sb.append(", ").append(avgWindSpeed);
        sb.append(", ").append(avgWindGust);
        sb.append(", ").append(sumRainfall);
        sb.append(", ").append(year);
        sb.append(", ").append(month);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
