/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.sql.Time;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LuxClimatology implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer month;
    private Integer day;
    private Time slotTime;
    private Double p95Lux;
    private Double p95LuxSmooth;
    private Integer sampleCount;
    private Timestamp updatedAt;

    public LuxClimatology() {}

    public LuxClimatology(LuxClimatology value) {
        this.month = value.month;
        this.day = value.day;
        this.slotTime = value.slotTime;
        this.p95Lux = value.p95Lux;
        this.p95LuxSmooth = value.p95LuxSmooth;
        this.sampleCount = value.sampleCount;
        this.updatedAt = value.updatedAt;
    }

    public LuxClimatology(
        Integer month,
        Integer day,
        Time slotTime,
        Double p95Lux,
        Double p95LuxSmooth,
        Integer sampleCount,
        Timestamp updatedAt
    ) {
        this.month = month;
        this.day = day;
        this.slotTime = slotTime;
        this.p95Lux = p95Lux;
        this.p95LuxSmooth = p95LuxSmooth;
        this.sampleCount = sampleCount;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.month</code>.
     */
    public Integer getMonth() {
        return this.month;
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.month</code>.
     */
    public void setMonth(Integer month) {
        this.month = month;
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.day</code>.
     */
    public Integer getDay() {
        return this.day;
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.day</code>.
     */
    public void setDay(Integer day) {
        this.day = day;
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.slot_time</code>.
     */
    public Time getSlotTime() {
        return this.slotTime;
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.slot_time</code>.
     */
    public void setSlotTime(Time slotTime) {
        this.slotTime = slotTime;
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.p95_lux</code>.
     */
    public Double getP95Lux() {
        return this.p95Lux;
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.p95_lux</code>.
     */
    public void setP95Lux(Double p95Lux) {
        this.p95Lux = p95Lux;
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.p95_lux_smooth</code>.
     */
    public Double getP95LuxSmooth() {
        return this.p95LuxSmooth;
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.p95_lux_smooth</code>.
     */
    public void setP95LuxSmooth(Double p95LuxSmooth) {
        this.p95LuxSmooth = p95LuxSmooth;
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.sample_count</code>.
     */
    public Integer getSampleCount() {
        return this.sampleCount;
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.sample_count</code>.
     */
    public void setSampleCount(Integer sampleCount) {
        this.sampleCount = sampleCount;
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return this.updatedAt;
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final LuxClimatology other = (LuxClimatology) obj;
        if (this.month == null) {
            if (other.month != null)
                return false;
        }
        else if (!this.month.equals(other.month))
            return false;
        if (this.day == null) {
            if (other.day != null)
                return false;
        }
        else if (!this.day.equals(other.day))
            return false;
        if (this.slotTime == null) {
            if (other.slotTime != null)
                return false;
        }
        else if (!this.slotTime.equals(other.slotTime))
            return false;
        if (this.p95Lux == null) {
            if (other.p95Lux != null)
                return false;
        }
        else if (!this.p95Lux.equals(other.p95Lux))
            return false;
        if (this.p95LuxSmooth == null) {
            if (other.p95LuxSmooth != null)
                return false;
        }
        else if (!this.p95LuxSmooth.equals(other.p95LuxSmooth))
            return false;
        if (this.sampleCount == null) {
            if (other.sampleCount != null)
                return false;
        }
        else if (!this.sampleCount.equals(other.sampleCount))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.month == null) ? 0 : this.month.hashCode());
        result = prime * result + ((this.day == null) ? 0 : this.day.hashCode());
        result = prime * result + ((this.slotTime == null) ? 0 : this.slotTime.hashCode());
        result = prime * result + ((this.p95Lux == null) ? 0 : this.p95Lux.hashCode());
        result = prime * result + ((this.p95LuxSmooth == null) ? 0 : this.p95LuxSmooth.hashCode());
        result = prime * result + ((this.sampleCount == null) ? 0 : this.sampleCount.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LuxClimatology (");

        sb.append(month);
        sb.append(", ").append(day);
        sb.append(", ").append(slotTime);
        sb.append(", ").append(p95Lux);
        sb.append(", ").append(p95LuxSmooth);
        sb.append(", ").append(sampleCount);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
