/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Measurements implements Serializable {

    private static final long serialVersionUID = -1937861282;

    private Long       id;
    private BigDecimal ambientTemp;
    private BigDecimal groundTemp;
    private BigDecimal pressure;
    private BigDecimal humidity;
    private BigDecimal windAverage;
    private BigDecimal windSpeed;
    private BigDecimal windGust;
    private BigDecimal rainfall;
    private BigDecimal piTemp;
    private Boolean    uploadedWu;
    private Timestamp  created;

    public Measurements() {}

    public Measurements(Measurements value) {
        this.id = value.id;
        this.ambientTemp = value.ambientTemp;
        this.groundTemp = value.groundTemp;
        this.pressure = value.pressure;
        this.humidity = value.humidity;
        this.windAverage = value.windAverage;
        this.windSpeed = value.windSpeed;
        this.windGust = value.windGust;
        this.rainfall = value.rainfall;
        this.piTemp = value.piTemp;
        this.uploadedWu = value.uploadedWu;
        this.created = value.created;
    }

    public Measurements(
        Long       id,
        BigDecimal ambientTemp,
        BigDecimal groundTemp,
        BigDecimal pressure,
        BigDecimal humidity,
        BigDecimal windAverage,
        BigDecimal windSpeed,
        BigDecimal windGust,
        BigDecimal rainfall,
        BigDecimal piTemp,
        Boolean    uploadedWu,
        Timestamp  created
    ) {
        this.id = id;
        this.ambientTemp = ambientTemp;
        this.groundTemp = groundTemp;
        this.pressure = pressure;
        this.humidity = humidity;
        this.windAverage = windAverage;
        this.windSpeed = windSpeed;
        this.windGust = windGust;
        this.rainfall = rainfall;
        this.piTemp = piTemp;
        this.uploadedWu = uploadedWu;
        this.created = created;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public BigDecimal getAmbientTemp() {
        return this.ambientTemp;
    }

    public void setAmbientTemp(BigDecimal ambientTemp) {
        this.ambientTemp = ambientTemp;
    }

    public BigDecimal getGroundTemp() {
        return this.groundTemp;
    }

    public void setGroundTemp(BigDecimal groundTemp) {
        this.groundTemp = groundTemp;
    }

    public BigDecimal getPressure() {
        return this.pressure;
    }

    public void setPressure(BigDecimal pressure) {
        this.pressure = pressure;
    }

    public BigDecimal getHumidity() {
        return this.humidity;
    }

    public void setHumidity(BigDecimal humidity) {
        this.humidity = humidity;
    }

    public BigDecimal getWindAverage() {
        return this.windAverage;
    }

    public void setWindAverage(BigDecimal windAverage) {
        this.windAverage = windAverage;
    }

    public BigDecimal getWindSpeed() {
        return this.windSpeed;
    }

    public void setWindSpeed(BigDecimal windSpeed) {
        this.windSpeed = windSpeed;
    }

    public BigDecimal getWindGust() {
        return this.windGust;
    }

    public void setWindGust(BigDecimal windGust) {
        this.windGust = windGust;
    }

    public BigDecimal getRainfall() {
        return this.rainfall;
    }

    public void setRainfall(BigDecimal rainfall) {
        this.rainfall = rainfall;
    }

    public BigDecimal getPiTemp() {
        return this.piTemp;
    }

    public void setPiTemp(BigDecimal piTemp) {
        this.piTemp = piTemp;
    }

    public Boolean getUploadedWu() {
        return this.uploadedWu;
    }

    public void setUploadedWu(Boolean uploadedWu) {
        this.uploadedWu = uploadedWu;
    }

    public Timestamp getCreated() {
        return this.created;
    }

    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Measurements (");

        sb.append(id);
        sb.append(", ").append(ambientTemp);
        sb.append(", ").append(groundTemp);
        sb.append(", ").append(pressure);
        sb.append(", ").append(humidity);
        sb.append(", ").append(windAverage);
        sb.append(", ").append(windSpeed);
        sb.append(", ").append(windGust);
        sb.append(", ").append(rainfall);
        sb.append(", ").append(piTemp);
        sb.append(", ").append(uploadedWu);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
