/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Measurements implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long       id;
    private BigDecimal ambientTemp;
    private BigDecimal groundTemp;
    private BigDecimal pressure;
    private BigDecimal humidity;
    private BigDecimal windAverage;
    private BigDecimal windSpeed;
    private BigDecimal windGust;
    private BigDecimal rainfall;
    private BigDecimal piTemp;
    private BigDecimal lux;
    private Boolean    uploadedWu;
    private Timestamp  created;

    public Measurements() {}

    public Measurements(Measurements value) {
        this.id = value.id;
        this.ambientTemp = value.ambientTemp;
        this.groundTemp = value.groundTemp;
        this.pressure = value.pressure;
        this.humidity = value.humidity;
        this.windAverage = value.windAverage;
        this.windSpeed = value.windSpeed;
        this.windGust = value.windGust;
        this.rainfall = value.rainfall;
        this.piTemp = value.piTemp;
        this.lux = value.lux;
        this.uploadedWu = value.uploadedWu;
        this.created = value.created;
    }

    public Measurements(
        Long       id,
        BigDecimal ambientTemp,
        BigDecimal groundTemp,
        BigDecimal pressure,
        BigDecimal humidity,
        BigDecimal windAverage,
        BigDecimal windSpeed,
        BigDecimal windGust,
        BigDecimal rainfall,
        BigDecimal piTemp,
        BigDecimal lux,
        Boolean    uploadedWu,
        Timestamp  created
    ) {
        this.id = id;
        this.ambientTemp = ambientTemp;
        this.groundTemp = groundTemp;
        this.pressure = pressure;
        this.humidity = humidity;
        this.windAverage = windAverage;
        this.windSpeed = windSpeed;
        this.windGust = windGust;
        this.rainfall = rainfall;
        this.piTemp = piTemp;
        this.lux = lux;
        this.uploadedWu = uploadedWu;
        this.created = created;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.ambient_temp</code>.
     */
    public BigDecimal getAmbientTemp() {
        return this.ambientTemp;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.ambient_temp</code>.
     */
    public void setAmbientTemp(BigDecimal ambientTemp) {
        this.ambientTemp = ambientTemp;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.ground_temp</code>.
     */
    public BigDecimal getGroundTemp() {
        return this.groundTemp;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.ground_temp</code>.
     */
    public void setGroundTemp(BigDecimal groundTemp) {
        this.groundTemp = groundTemp;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.pressure</code>.
     */
    public BigDecimal getPressure() {
        return this.pressure;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.pressure</code>.
     */
    public void setPressure(BigDecimal pressure) {
        this.pressure = pressure;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.humidity</code>.
     */
    public BigDecimal getHumidity() {
        return this.humidity;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.humidity</code>.
     */
    public void setHumidity(BigDecimal humidity) {
        this.humidity = humidity;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.wind_average</code>.
     */
    public BigDecimal getWindAverage() {
        return this.windAverage;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.wind_average</code>.
     */
    public void setWindAverage(BigDecimal windAverage) {
        this.windAverage = windAverage;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.wind_speed</code>.
     */
    public BigDecimal getWindSpeed() {
        return this.windSpeed;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.wind_speed</code>.
     */
    public void setWindSpeed(BigDecimal windSpeed) {
        this.windSpeed = windSpeed;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.wind_gust</code>.
     */
    public BigDecimal getWindGust() {
        return this.windGust;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.wind_gust</code>.
     */
    public void setWindGust(BigDecimal windGust) {
        this.windGust = windGust;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.rainfall</code>.
     */
    public BigDecimal getRainfall() {
        return this.rainfall;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.rainfall</code>.
     */
    public void setRainfall(BigDecimal rainfall) {
        this.rainfall = rainfall;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.pi_temp</code>.
     */
    public BigDecimal getPiTemp() {
        return this.piTemp;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.pi_temp</code>.
     */
    public void setPiTemp(BigDecimal piTemp) {
        this.piTemp = piTemp;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.lux</code>.
     */
    public BigDecimal getLux() {
        return this.lux;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.lux</code>.
     */
    public void setLux(BigDecimal lux) {
        this.lux = lux;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.uploaded_wu</code>.
     */
    public Boolean getUploadedWu() {
        return this.uploadedWu;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.uploaded_wu</code>.
     */
    public void setUploadedWu(Boolean uploadedWu) {
        this.uploadedWu = uploadedWu;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.created</code>.
     */
    public Timestamp getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.created</code>.
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Measurements (");

        sb.append(id);
        sb.append(", ").append(ambientTemp);
        sb.append(", ").append(groundTemp);
        sb.append(", ").append(pressure);
        sb.append(", ").append(humidity);
        sb.append(", ").append(windAverage);
        sb.append(", ").append(windSpeed);
        sb.append(", ").append(windGust);
        sb.append(", ").append(rainfall);
        sb.append(", ").append(piTemp);
        sb.append(", ").append(lux);
        sb.append(", ").append(uploadedWu);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
