/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Timestamp;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Measurements implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private BigDecimal ambientTemp;
    private BigDecimal groundTemp;
    private BigDecimal pressure;
    private BigDecimal humidity;
    private BigDecimal windAverage;
    private BigDecimal windSpeed;
    private BigDecimal windGust;
    private BigDecimal rainfall;
    private BigDecimal piTemp;
    private BigDecimal loftHumidity;
    private BigDecimal loftTemp;
    private BigDecimal lux;
    private Boolean uploadedWu;
    private Timestamp created;

    public Measurements() {}

    public Measurements(Measurements value) {
        this.id = value.id;
        this.ambientTemp = value.ambientTemp;
        this.groundTemp = value.groundTemp;
        this.pressure = value.pressure;
        this.humidity = value.humidity;
        this.windAverage = value.windAverage;
        this.windSpeed = value.windSpeed;
        this.windGust = value.windGust;
        this.rainfall = value.rainfall;
        this.piTemp = value.piTemp;
        this.loftHumidity = value.loftHumidity;
        this.loftTemp = value.loftTemp;
        this.lux = value.lux;
        this.uploadedWu = value.uploadedWu;
        this.created = value.created;
    }

    public Measurements(
        Long id,
        BigDecimal ambientTemp,
        BigDecimal groundTemp,
        BigDecimal pressure,
        BigDecimal humidity,
        BigDecimal windAverage,
        BigDecimal windSpeed,
        BigDecimal windGust,
        BigDecimal rainfall,
        BigDecimal piTemp,
        BigDecimal loftHumidity,
        BigDecimal loftTemp,
        BigDecimal lux,
        Boolean uploadedWu,
        Timestamp created
    ) {
        this.id = id;
        this.ambientTemp = ambientTemp;
        this.groundTemp = groundTemp;
        this.pressure = pressure;
        this.humidity = humidity;
        this.windAverage = windAverage;
        this.windSpeed = windSpeed;
        this.windGust = windGust;
        this.rainfall = rainfall;
        this.piTemp = piTemp;
        this.loftHumidity = loftHumidity;
        this.loftTemp = loftTemp;
        this.lux = lux;
        this.uploadedWu = uploadedWu;
        this.created = created;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.ambient_temp</code>.
     */
    public BigDecimal getAmbientTemp() {
        return this.ambientTemp;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.ambient_temp</code>.
     */
    public void setAmbientTemp(BigDecimal ambientTemp) {
        this.ambientTemp = ambientTemp;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.ground_temp</code>.
     */
    public BigDecimal getGroundTemp() {
        return this.groundTemp;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.ground_temp</code>.
     */
    public void setGroundTemp(BigDecimal groundTemp) {
        this.groundTemp = groundTemp;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.pressure</code>.
     */
    public BigDecimal getPressure() {
        return this.pressure;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.pressure</code>.
     */
    public void setPressure(BigDecimal pressure) {
        this.pressure = pressure;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.humidity</code>.
     */
    public BigDecimal getHumidity() {
        return this.humidity;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.humidity</code>.
     */
    public void setHumidity(BigDecimal humidity) {
        this.humidity = humidity;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.wind_average</code>.
     */
    public BigDecimal getWindAverage() {
        return this.windAverage;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.wind_average</code>.
     */
    public void setWindAverage(BigDecimal windAverage) {
        this.windAverage = windAverage;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.wind_speed</code>.
     */
    public BigDecimal getWindSpeed() {
        return this.windSpeed;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.wind_speed</code>.
     */
    public void setWindSpeed(BigDecimal windSpeed) {
        this.windSpeed = windSpeed;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.wind_gust</code>.
     */
    public BigDecimal getWindGust() {
        return this.windGust;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.wind_gust</code>.
     */
    public void setWindGust(BigDecimal windGust) {
        this.windGust = windGust;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.rainfall</code>.
     */
    public BigDecimal getRainfall() {
        return this.rainfall;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.rainfall</code>.
     */
    public void setRainfall(BigDecimal rainfall) {
        this.rainfall = rainfall;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.pi_temp</code>.
     */
    public BigDecimal getPiTemp() {
        return this.piTemp;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.pi_temp</code>.
     */
    public void setPiTemp(BigDecimal piTemp) {
        this.piTemp = piTemp;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.loft_humidity</code>.
     */
    public BigDecimal getLoftHumidity() {
        return this.loftHumidity;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.loft_humidity</code>.
     */
    public void setLoftHumidity(BigDecimal loftHumidity) {
        this.loftHumidity = loftHumidity;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.loft_temp</code>.
     */
    public BigDecimal getLoftTemp() {
        return this.loftTemp;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.loft_temp</code>.
     */
    public void setLoftTemp(BigDecimal loftTemp) {
        this.loftTemp = loftTemp;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.lux</code>.
     */
    public BigDecimal getLux() {
        return this.lux;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.lux</code>.
     */
    public void setLux(BigDecimal lux) {
        this.lux = lux;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.uploaded_wu</code>.
     */
    public Boolean getUploadedWu() {
        return this.uploadedWu;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.uploaded_wu</code>.
     */
    public void setUploadedWu(Boolean uploadedWu) {
        this.uploadedWu = uploadedWu;
    }

    /**
     * Getter for <code>weatherstation_db.measurements.created</code>.
     */
    public Timestamp getCreated() {
        return this.created;
    }

    /**
     * Setter for <code>weatherstation_db.measurements.created</code>.
     */
    public void setCreated(Timestamp created) {
        this.created = created;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Measurements other = (Measurements) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ambientTemp == null) {
            if (other.ambientTemp != null)
                return false;
        }
        else if (!this.ambientTemp.equals(other.ambientTemp))
            return false;
        if (this.groundTemp == null) {
            if (other.groundTemp != null)
                return false;
        }
        else if (!this.groundTemp.equals(other.groundTemp))
            return false;
        if (this.pressure == null) {
            if (other.pressure != null)
                return false;
        }
        else if (!this.pressure.equals(other.pressure))
            return false;
        if (this.humidity == null) {
            if (other.humidity != null)
                return false;
        }
        else if (!this.humidity.equals(other.humidity))
            return false;
        if (this.windAverage == null) {
            if (other.windAverage != null)
                return false;
        }
        else if (!this.windAverage.equals(other.windAverage))
            return false;
        if (this.windSpeed == null) {
            if (other.windSpeed != null)
                return false;
        }
        else if (!this.windSpeed.equals(other.windSpeed))
            return false;
        if (this.windGust == null) {
            if (other.windGust != null)
                return false;
        }
        else if (!this.windGust.equals(other.windGust))
            return false;
        if (this.rainfall == null) {
            if (other.rainfall != null)
                return false;
        }
        else if (!this.rainfall.equals(other.rainfall))
            return false;
        if (this.piTemp == null) {
            if (other.piTemp != null)
                return false;
        }
        else if (!this.piTemp.equals(other.piTemp))
            return false;
        if (this.loftHumidity == null) {
            if (other.loftHumidity != null)
                return false;
        }
        else if (!this.loftHumidity.equals(other.loftHumidity))
            return false;
        if (this.loftTemp == null) {
            if (other.loftTemp != null)
                return false;
        }
        else if (!this.loftTemp.equals(other.loftTemp))
            return false;
        if (this.lux == null) {
            if (other.lux != null)
                return false;
        }
        else if (!this.lux.equals(other.lux))
            return false;
        if (this.uploadedWu == null) {
            if (other.uploadedWu != null)
                return false;
        }
        else if (!this.uploadedWu.equals(other.uploadedWu))
            return false;
        if (this.created == null) {
            if (other.created != null)
                return false;
        }
        else if (!this.created.equals(other.created))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ambientTemp == null) ? 0 : this.ambientTemp.hashCode());
        result = prime * result + ((this.groundTemp == null) ? 0 : this.groundTemp.hashCode());
        result = prime * result + ((this.pressure == null) ? 0 : this.pressure.hashCode());
        result = prime * result + ((this.humidity == null) ? 0 : this.humidity.hashCode());
        result = prime * result + ((this.windAverage == null) ? 0 : this.windAverage.hashCode());
        result = prime * result + ((this.windSpeed == null) ? 0 : this.windSpeed.hashCode());
        result = prime * result + ((this.windGust == null) ? 0 : this.windGust.hashCode());
        result = prime * result + ((this.rainfall == null) ? 0 : this.rainfall.hashCode());
        result = prime * result + ((this.piTemp == null) ? 0 : this.piTemp.hashCode());
        result = prime * result + ((this.loftHumidity == null) ? 0 : this.loftHumidity.hashCode());
        result = prime * result + ((this.loftTemp == null) ? 0 : this.loftTemp.hashCode());
        result = prime * result + ((this.lux == null) ? 0 : this.lux.hashCode());
        result = prime * result + ((this.uploadedWu == null) ? 0 : this.uploadedWu.hashCode());
        result = prime * result + ((this.created == null) ? 0 : this.created.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Measurements (");

        sb.append(id);
        sb.append(", ").append(ambientTemp);
        sb.append(", ").append(groundTemp);
        sb.append(", ").append(pressure);
        sb.append(", ").append(humidity);
        sb.append(", ").append(windAverage);
        sb.append(", ").append(windSpeed);
        sb.append(", ").append(windGust);
        sb.append(", ").append(rainfall);
        sb.append(", ").append(piTemp);
        sb.append(", ").append(loftHumidity);
        sb.append(", ").append(loftTemp);
        sb.append(", ").append(lux);
        sb.append(", ").append(uploadedWu);
        sb.append(", ").append(created);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
