/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


// @formatter:off
/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ViewStatsDaily implements Serializable {

    private static final long serialVersionUID = 1843960517;

    private String agrtype;
    private Double ambientTemp;
    private Double groundTemp;
    private Double pressure;
    private Double humidity;
    private Double windAverage;
    private Double windSpeed;
    private Double windGust;
    private Double rainfall;
    private String date;

    public ViewStatsDaily() {}

    public ViewStatsDaily(ViewStatsDaily value) {
        this.agrtype = value.agrtype;
        this.ambientTemp = value.ambientTemp;
        this.groundTemp = value.groundTemp;
        this.pressure = value.pressure;
        this.humidity = value.humidity;
        this.windAverage = value.windAverage;
        this.windSpeed = value.windSpeed;
        this.windGust = value.windGust;
        this.rainfall = value.rainfall;
        this.date = value.date;
    }

    public ViewStatsDaily(
        String agrtype,
        Double ambientTemp,
        Double groundTemp,
        Double pressure,
        Double humidity,
        Double windAverage,
        Double windSpeed,
        Double windGust,
        Double rainfall,
        String date
    ) {
        this.agrtype = agrtype;
        this.ambientTemp = ambientTemp;
        this.groundTemp = groundTemp;
        this.pressure = pressure;
        this.humidity = humidity;
        this.windAverage = windAverage;
        this.windSpeed = windSpeed;
        this.windGust = windGust;
        this.rainfall = rainfall;
        this.date = date;
    }

    public String getAgrtype() {
        return this.agrtype;
    }

    public void setAgrtype(String agrtype) {
        this.agrtype = agrtype;
    }

    public Double getAmbientTemp() {
        return this.ambientTemp;
    }

    public void setAmbientTemp(Double ambientTemp) {
        this.ambientTemp = ambientTemp;
    }

    public Double getGroundTemp() {
        return this.groundTemp;
    }

    public void setGroundTemp(Double groundTemp) {
        this.groundTemp = groundTemp;
    }

    public Double getPressure() {
        return this.pressure;
    }

    public void setPressure(Double pressure) {
        this.pressure = pressure;
    }

    public Double getHumidity() {
        return this.humidity;
    }

    public void setHumidity(Double humidity) {
        this.humidity = humidity;
    }

    public Double getWindAverage() {
        return this.windAverage;
    }

    public void setWindAverage(Double windAverage) {
        this.windAverage = windAverage;
    }

    public Double getWindSpeed() {
        return this.windSpeed;
    }

    public void setWindSpeed(Double windSpeed) {
        this.windSpeed = windSpeed;
    }

    public Double getWindGust() {
        return this.windGust;
    }

    public void setWindGust(Double windGust) {
        this.windGust = windGust;
    }

    public Double getRainfall() {
        return this.rainfall;
    }

    public void setRainfall(Double rainfall) {
        this.rainfall = rainfall;
    }

    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewStatsDaily (");

        sb.append(agrtype);
        sb.append(", ").append(ambientTemp);
        sb.append(", ").append(groundTemp);
        sb.append(", ").append(pressure);
        sb.append(", ").append(humidity);
        sb.append(", ").append(windAverage);
        sb.append(", ").append(windSpeed);
        sb.append(", ").append(windGust);
        sb.append(", ").append(rainfall);
        sb.append(", ").append(date);

        sb.append(")");
        return sb.toString();
    }
// @formatter:on
}
