/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewPeriods implements Serializable {

    private static final long serialVersionUID = 1L;

    private String type;
    private Date startDate;
    private Date endDate;
    private Long consecutiveDays;
    private BigDecimal totalRainAmount;

    public ViewPeriods() {}

    public ViewPeriods(ViewPeriods value) {
        this.type = value.type;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.consecutiveDays = value.consecutiveDays;
        this.totalRainAmount = value.totalRainAmount;
    }

    public ViewPeriods(
        String type,
        Date startDate,
        Date endDate,
        Long consecutiveDays,
        BigDecimal totalRainAmount
    ) {
        this.type = type;
        this.startDate = startDate;
        this.endDate = endDate;
        this.consecutiveDays = consecutiveDays;
        this.totalRainAmount = totalRainAmount;
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.type</code>.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Setter for <code>weatherstation_db.view_periods.type</code>.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.start_date</code>.
     */
    public Date getStartDate() {
        return this.startDate;
    }

    /**
     * Setter for <code>weatherstation_db.view_periods.start_date</code>.
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.end_date</code>.
     */
    public Date getEndDate() {
        return this.endDate;
    }

    /**
     * Setter for <code>weatherstation_db.view_periods.end_date</code>.
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.consecutive_days</code>.
     */
    public Long getConsecutiveDays() {
        return this.consecutiveDays;
    }

    /**
     * Setter for <code>weatherstation_db.view_periods.consecutive_days</code>.
     */
    public void setConsecutiveDays(Long consecutiveDays) {
        this.consecutiveDays = consecutiveDays;
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.total_rain_amount</code>.
     */
    public BigDecimal getTotalRainAmount() {
        return this.totalRainAmount;
    }

    /**
     * Setter for <code>weatherstation_db.view_periods.total_rain_amount</code>.
     */
    public void setTotalRainAmount(BigDecimal totalRainAmount) {
        this.totalRainAmount = totalRainAmount;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ViewPeriods other = (ViewPeriods) obj;
        if (this.type == null) {
            if (other.type != null)
                return false;
        }
        else if (!this.type.equals(other.type))
            return false;
        if (this.startDate == null) {
            if (other.startDate != null)
                return false;
        }
        else if (!this.startDate.equals(other.startDate))
            return false;
        if (this.endDate == null) {
            if (other.endDate != null)
                return false;
        }
        else if (!this.endDate.equals(other.endDate))
            return false;
        if (this.consecutiveDays == null) {
            if (other.consecutiveDays != null)
                return false;
        }
        else if (!this.consecutiveDays.equals(other.consecutiveDays))
            return false;
        if (this.totalRainAmount == null) {
            if (other.totalRainAmount != null)
                return false;
        }
        else if (!this.totalRainAmount.equals(other.totalRainAmount))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.type == null) ? 0 : this.type.hashCode());
        result = prime * result + ((this.startDate == null) ? 0 : this.startDate.hashCode());
        result = prime * result + ((this.endDate == null) ? 0 : this.endDate.hashCode());
        result = prime * result + ((this.consecutiveDays == null) ? 0 : this.consecutiveDays.hashCode());
        result = prime * result + ((this.totalRainAmount == null) ? 0 : this.totalRainAmount.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ViewPeriods (");

        sb.append(type);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(consecutiveDays);
        sb.append(", ").append(totalRainAmount);

        sb.append(")");
        return sb.toString();
    }
    // @formatter:on
}
