/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.records;


import java.math.BigDecimal;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.raubach.weatherstation.server.database.codegen.tables.AggregatedYearMonth;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AggregatedYearMonthRecord extends UpdatableRecordImpl<AggregatedYearMonthRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_ambient_temp</code>.
     */
    public void setAvgAmbientTemp(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_ambient_temp</code>.
     */
    public BigDecimal getAvgAmbientTemp() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_ground_temp</code>.
     */
    public void setAvgGroundTemp(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_ground_temp</code>.
     */
    public BigDecimal getAvgGroundTemp() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_loft_humidity</code>.
     */
    public void setAvgLoftHumidity(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_loft_humidity</code>.
     */
    public BigDecimal getAvgLoftHumidity() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_loft_temp</code>.
     */
    public void setAvgLoftTemp(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_loft_temp</code>.
     */
    public BigDecimal getAvgLoftTemp() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>weatherstation_db.aggregated_year_month.avg_lux</code>.
     */
    public void setAvgLux(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>weatherstation_db.aggregated_year_month.avg_lux</code>.
     */
    public BigDecimal getAvgLux() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_pressure</code>.
     */
    public void setAvgPressure(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_pressure</code>.
     */
    public BigDecimal getAvgPressure() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_humidity</code>.
     */
    public void setAvgHumidity(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_humidity</code>.
     */
    public BigDecimal getAvgHumidity() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_speed</code>.
     */
    public void setAvgWindSpeed(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_speed</code>.
     */
    public BigDecimal getAvgWindSpeed() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_gust</code>.
     */
    public void setAvgWindGust(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_gust</code>.
     */
    public BigDecimal getAvgWindGust() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.sum_rainfall</code>.
     */
    public void setSumRainfall(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.sum_rainfall</code>.
     */
    public BigDecimal getSumRainfall() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>weatherstation_db.aggregated_year_month.year</code>.
     */
    public void setYear(Short value) {
        set(10, value);
    }

    /**
     * Getter for <code>weatherstation_db.aggregated_year_month.year</code>.
     */
    public Short getYear() {
        return (Short) get(10);
    }

    /**
     * Setter for <code>weatherstation_db.aggregated_year_month.month</code>.
     */
    public void setMonth(Short value) {
        set(11, value);
    }

    /**
     * Getter for <code>weatherstation_db.aggregated_year_month.month</code>.
     */
    public Short getMonth() {
        return (Short) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Short, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AggregatedYearMonthRecord
     */
    public AggregatedYearMonthRecord() {
        super(AggregatedYearMonth.AGGREGATED_YEAR_MONTH);
    }

    /**
     * Create a detached, initialised AggregatedYearMonthRecord
     */
    public AggregatedYearMonthRecord(BigDecimal avgAmbientTemp, BigDecimal avgGroundTemp, BigDecimal avgLoftHumidity, BigDecimal avgLoftTemp, BigDecimal avgLux, BigDecimal avgPressure, BigDecimal avgHumidity, BigDecimal avgWindSpeed, BigDecimal avgWindGust, BigDecimal sumRainfall, Short year, Short month) {
        super(AggregatedYearMonth.AGGREGATED_YEAR_MONTH);

        setAvgAmbientTemp(avgAmbientTemp);
        setAvgGroundTemp(avgGroundTemp);
        setAvgLoftHumidity(avgLoftHumidity);
        setAvgLoftTemp(avgLoftTemp);
        setAvgLux(avgLux);
        setAvgPressure(avgPressure);
        setAvgHumidity(avgHumidity);
        setAvgWindSpeed(avgWindSpeed);
        setAvgWindGust(avgWindGust);
        setSumRainfall(sumRainfall);
        setYear(year);
        setMonth(month);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised AggregatedYearMonthRecord
     */
    public AggregatedYearMonthRecord(uk.co.raubach.weatherstation.server.database.codegen.tables.pojos.AggregatedYearMonth value) {
        super(AggregatedYearMonth.AGGREGATED_YEAR_MONTH);

        if (value != null) {
            setAvgAmbientTemp(value.getAvgAmbientTemp());
            setAvgGroundTemp(value.getAvgGroundTemp());
            setAvgLoftHumidity(value.getAvgLoftHumidity());
            setAvgLoftTemp(value.getAvgLoftTemp());
            setAvgLux(value.getAvgLux());
            setAvgPressure(value.getAvgPressure());
            setAvgHumidity(value.getAvgHumidity());
            setAvgWindSpeed(value.getAvgWindSpeed());
            setAvgWindGust(value.getAvgWindGust());
            setSumRainfall(value.getSumRainfall());
            setYear(value.getYear());
            setMonth(value.getMonth());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
