/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.records;


import java.math.BigDecimal;

import org.jooq.Field;
import org.jooq.Record10;
import org.jooq.Record2;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.raubach.weatherstation.server.database.codegen.tables.AggregatedYearMonth;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AggregatedYearMonthRecord extends UpdatableRecordImpl<AggregatedYearMonthRecord> implements Record10<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Short, Short> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_ambient_temp</code>.
     */
    public void setAvgAmbientTemp(BigDecimal value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_ambient_temp</code>.
     */
    public BigDecimal getAvgAmbientTemp() {
        return (BigDecimal) get(0);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_ground_temp</code>.
     */
    public void setAvgGroundTemp(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_ground_temp</code>.
     */
    public BigDecimal getAvgGroundTemp() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>weatherstation_db.aggregated_year_month.avg_lux</code>.
     */
    public void setAvgLux(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>weatherstation_db.aggregated_year_month.avg_lux</code>.
     */
    public BigDecimal getAvgLux() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_pressure</code>.
     */
    public void setAvgPressure(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_pressure</code>.
     */
    public BigDecimal getAvgPressure() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_humidity</code>.
     */
    public void setAvgHumidity(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_humidity</code>.
     */
    public BigDecimal getAvgHumidity() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_speed</code>.
     */
    public void setAvgWindSpeed(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_speed</code>.
     */
    public BigDecimal getAvgWindSpeed() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_gust</code>.
     */
    public void setAvgWindGust(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.avg_wind_gust</code>.
     */
    public BigDecimal getAvgWindGust() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for
     * <code>weatherstation_db.aggregated_year_month.sum_rainfall</code>.
     */
    public void setSumRainfall(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>weatherstation_db.aggregated_year_month.sum_rainfall</code>.
     */
    public BigDecimal getSumRainfall() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>weatherstation_db.aggregated_year_month.year</code>.
     */
    public void setYear(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>weatherstation_db.aggregated_year_month.year</code>.
     */
    public Short getYear() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>weatherstation_db.aggregated_year_month.month</code>.
     */
    public void setMonth(Short value) {
        set(9, value);
    }

    /**
     * Getter for <code>weatherstation_db.aggregated_year_month.month</code>.
     */
    public Short getMonth() {
        return (Short) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Short, Short> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row10<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Short, Short> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    @Override
    public Row10<BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, Short, Short> valuesRow() {
        return (Row10) super.valuesRow();
    }

    @Override
    public Field<BigDecimal> field1() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.AVG_AMBIENT_TEMP;
    }

    @Override
    public Field<BigDecimal> field2() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.AVG_GROUND_TEMP;
    }

    @Override
    public Field<BigDecimal> field3() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.AVG_LUX;
    }

    @Override
    public Field<BigDecimal> field4() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.AVG_PRESSURE;
    }

    @Override
    public Field<BigDecimal> field5() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.AVG_HUMIDITY;
    }

    @Override
    public Field<BigDecimal> field6() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.AVG_WIND_SPEED;
    }

    @Override
    public Field<BigDecimal> field7() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.AVG_WIND_GUST;
    }

    @Override
    public Field<BigDecimal> field8() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.SUM_RAINFALL;
    }

    @Override
    public Field<Short> field9() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.YEAR;
    }

    @Override
    public Field<Short> field10() {
        return AggregatedYearMonth.AGGREGATED_YEAR_MONTH.MONTH;
    }

    @Override
    public BigDecimal component1() {
        return getAvgAmbientTemp();
    }

    @Override
    public BigDecimal component2() {
        return getAvgGroundTemp();
    }

    @Override
    public BigDecimal component3() {
        return getAvgLux();
    }

    @Override
    public BigDecimal component4() {
        return getAvgPressure();
    }

    @Override
    public BigDecimal component5() {
        return getAvgHumidity();
    }

    @Override
    public BigDecimal component6() {
        return getAvgWindSpeed();
    }

    @Override
    public BigDecimal component7() {
        return getAvgWindGust();
    }

    @Override
    public BigDecimal component8() {
        return getSumRainfall();
    }

    @Override
    public Short component9() {
        return getYear();
    }

    @Override
    public Short component10() {
        return getMonth();
    }

    @Override
    public BigDecimal value1() {
        return getAvgAmbientTemp();
    }

    @Override
    public BigDecimal value2() {
        return getAvgGroundTemp();
    }

    @Override
    public BigDecimal value3() {
        return getAvgLux();
    }

    @Override
    public BigDecimal value4() {
        return getAvgPressure();
    }

    @Override
    public BigDecimal value5() {
        return getAvgHumidity();
    }

    @Override
    public BigDecimal value6() {
        return getAvgWindSpeed();
    }

    @Override
    public BigDecimal value7() {
        return getAvgWindGust();
    }

    @Override
    public BigDecimal value8() {
        return getSumRainfall();
    }

    @Override
    public Short value9() {
        return getYear();
    }

    @Override
    public Short value10() {
        return getMonth();
    }

    @Override
    public AggregatedYearMonthRecord value1(BigDecimal value) {
        setAvgAmbientTemp(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord value2(BigDecimal value) {
        setAvgGroundTemp(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord value3(BigDecimal value) {
        setAvgLux(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord value4(BigDecimal value) {
        setAvgPressure(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord value5(BigDecimal value) {
        setAvgHumidity(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord value6(BigDecimal value) {
        setAvgWindSpeed(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord value7(BigDecimal value) {
        setAvgWindGust(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord value8(BigDecimal value) {
        setSumRainfall(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord value9(Short value) {
        setYear(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord value10(Short value) {
        setMonth(value);
        return this;
    }

    @Override
    public AggregatedYearMonthRecord values(BigDecimal value1, BigDecimal value2, BigDecimal value3, BigDecimal value4, BigDecimal value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, Short value9, Short value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AggregatedYearMonthRecord
     */
    public AggregatedYearMonthRecord() {
        super(AggregatedYearMonth.AGGREGATED_YEAR_MONTH);
    }

    /**
     * Create a detached, initialised AggregatedYearMonthRecord
     */
    public AggregatedYearMonthRecord(BigDecimal avgAmbientTemp, BigDecimal avgGroundTemp, BigDecimal avgLux, BigDecimal avgPressure, BigDecimal avgHumidity, BigDecimal avgWindSpeed, BigDecimal avgWindGust, BigDecimal sumRainfall, Short year, Short month) {
        super(AggregatedYearMonth.AGGREGATED_YEAR_MONTH);

        setAvgAmbientTemp(avgAmbientTemp);
        setAvgGroundTemp(avgGroundTemp);
        setAvgLux(avgLux);
        setAvgPressure(avgPressure);
        setAvgHumidity(avgHumidity);
        setAvgWindSpeed(avgWindSpeed);
        setAvgWindGust(avgWindGust);
        setSumRainfall(sumRainfall);
        setYear(year);
        setMonth(month);
    }

    /**
     * Create a detached, initialised AggregatedYearMonthRecord
     */
    public AggregatedYearMonthRecord(uk.co.raubach.weatherstation.server.database.codegen.tables.pojos.AggregatedYearMonth value) {
        super(AggregatedYearMonth.AGGREGATED_YEAR_MONTH);

        if (value != null) {
            setAvgAmbientTemp(value.getAvgAmbientTemp());
            setAvgGroundTemp(value.getAvgGroundTemp());
            setAvgLux(value.getAvgLux());
            setAvgPressure(value.getAvgPressure());
            setAvgHumidity(value.getAvgHumidity());
            setAvgWindSpeed(value.getAvgWindSpeed());
            setAvgWindGust(value.getAvgWindGust());
            setSumRainfall(value.getSumRainfall());
            setYear(value.getYear());
            setMonth(value.getMonth());
        }
    }
    // @formatter:on
}
