/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.records;


import java.sql.Time;
import java.sql.Timestamp;

import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.raubach.weatherstation.server.database.codegen.tables.LuxClimatology;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LuxClimatologyRecord extends UpdatableRecordImpl<LuxClimatologyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>weatherstation_db.lux_climatology.month</code>.
     */
    public void setMonth(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.month</code>.
     */
    public Integer getMonth() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.day</code>.
     */
    public void setDay(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.day</code>.
     */
    public Integer getDay() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.slot_time</code>.
     */
    public void setSlotTime(Time value) {
        set(2, value);
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.slot_time</code>.
     */
    public Time getSlotTime() {
        return (Time) get(2);
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.p95_lux</code>.
     */
    public void setP95Lux(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.p95_lux</code>.
     */
    public Double getP95Lux() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.p95_lux_smooth</code>.
     */
    public void setP95LuxSmooth(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.p95_lux_smooth</code>.
     */
    public Double getP95LuxSmooth() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.sample_count</code>.
     */
    public void setSampleCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.sample_count</code>.
     */
    public Integer getSampleCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>weatherstation_db.lux_climatology.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>weatherstation_db.lux_climatology.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Integer, Integer, Time> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LuxClimatologyRecord
     */
    public LuxClimatologyRecord() {
        super(LuxClimatology.LUX_CLIMATOLOGY);
    }

    /**
     * Create a detached, initialised LuxClimatologyRecord
     */
    public LuxClimatologyRecord(Integer month, Integer day, Time slotTime, Double p95Lux, Double p95LuxSmooth, Integer sampleCount, Timestamp updatedAt) {
        super(LuxClimatology.LUX_CLIMATOLOGY);

        setMonth(month);
        setDay(day);
        setSlotTime(slotTime);
        setP95Lux(p95Lux);
        setP95LuxSmooth(p95LuxSmooth);
        setSampleCount(sampleCount);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised LuxClimatologyRecord
     */
    public LuxClimatologyRecord(uk.co.raubach.weatherstation.server.database.codegen.tables.pojos.LuxClimatology value) {
        super(LuxClimatology.LUX_CLIMATOLOGY);

        if (value != null) {
            setMonth(value.getMonth());
            setDay(value.getDay());
            setSlotTime(value.getSlotTime());
            setP95Lux(value.getP95Lux());
            setP95LuxSmooth(value.getP95LuxSmooth());
            setSampleCount(value.getSampleCount());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
