/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.records;


import java.math.BigDecimal;
import java.sql.Timestamp;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import uk.co.raubach.weatherstation.server.database.codegen.tables.Measurements;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MeasurementsRecord extends UpdatableRecordImpl<MeasurementsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>weatherstation_db.measurements.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.ambient_temp</code>.
     */
    public void setAmbientTemp(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.ambient_temp</code>.
     */
    public BigDecimal getAmbientTemp() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.ground_temp</code>.
     */
    public void setGroundTemp(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.ground_temp</code>.
     */
    public BigDecimal getGroundTemp() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.pressure</code>.
     */
    public void setPressure(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.pressure</code>.
     */
    public BigDecimal getPressure() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.humidity</code>.
     */
    public void setHumidity(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.humidity</code>.
     */
    public BigDecimal getHumidity() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.wind_average</code>.
     */
    public void setWindAverage(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.wind_average</code>.
     */
    public BigDecimal getWindAverage() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.wind_speed</code>.
     */
    public void setWindSpeed(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.wind_speed</code>.
     */
    public BigDecimal getWindSpeed() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.wind_gust</code>.
     */
    public void setWindGust(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.wind_gust</code>.
     */
    public BigDecimal getWindGust() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.rainfall</code>.
     */
    public void setRainfall(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.rainfall</code>.
     */
    public BigDecimal getRainfall() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.pi_temp</code>.
     */
    public void setPiTemp(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.pi_temp</code>.
     */
    public BigDecimal getPiTemp() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.loft_humidity</code>.
     */
    public void setLoftHumidity(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.loft_humidity</code>.
     */
    public BigDecimal getLoftHumidity() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.loft_temp</code>.
     */
    public void setLoftTemp(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.loft_temp</code>.
     */
    public BigDecimal getLoftTemp() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.lux</code>.
     */
    public void setLux(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.lux</code>.
     */
    public BigDecimal getLux() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.uploaded_wu</code>.
     */
    public void setUploadedWu(Boolean value) {
        set(13, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.uploaded_wu</code>.
     */
    public Boolean getUploadedWu() {
        return (Boolean) get(13);
    }

    /**
     * Setter for <code>weatherstation_db.measurements.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>weatherstation_db.measurements.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MeasurementsRecord
     */
    public MeasurementsRecord() {
        super(Measurements.MEASUREMENTS);
    }

    /**
     * Create a detached, initialised MeasurementsRecord
     */
    public MeasurementsRecord(Long id, BigDecimal ambientTemp, BigDecimal groundTemp, BigDecimal pressure, BigDecimal humidity, BigDecimal windAverage, BigDecimal windSpeed, BigDecimal windGust, BigDecimal rainfall, BigDecimal piTemp, BigDecimal loftHumidity, BigDecimal loftTemp, BigDecimal lux, Boolean uploadedWu, Timestamp created) {
        super(Measurements.MEASUREMENTS);

        setId(id);
        setAmbientTemp(ambientTemp);
        setGroundTemp(groundTemp);
        setPressure(pressure);
        setHumidity(humidity);
        setWindAverage(windAverage);
        setWindSpeed(windSpeed);
        setWindGust(windGust);
        setRainfall(rainfall);
        setPiTemp(piTemp);
        setLoftHumidity(loftHumidity);
        setLoftTemp(loftTemp);
        setLux(lux);
        setUploadedWu(uploadedWu);
        setCreated(created);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised MeasurementsRecord
     */
    public MeasurementsRecord(uk.co.raubach.weatherstation.server.database.codegen.tables.pojos.Measurements value) {
        super(Measurements.MEASUREMENTS);

        if (value != null) {
            setId(value.getId());
            setAmbientTemp(value.getAmbientTemp());
            setGroundTemp(value.getGroundTemp());
            setPressure(value.getPressure());
            setHumidity(value.getHumidity());
            setWindAverage(value.getWindAverage());
            setWindSpeed(value.getWindSpeed());
            setWindGust(value.getWindGust());
            setRainfall(value.getRainfall());
            setPiTemp(value.getPiTemp());
            setLoftHumidity(value.getLoftHumidity());
            setLoftTemp(value.getLoftTemp());
            setLux(value.getLux());
            setUploadedWu(value.getUploadedWu());
            setCreated(value.getCreated());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
