/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen.tables.records;


import java.math.BigDecimal;
import java.sql.Date;

import org.jooq.impl.TableRecordImpl;

import uk.co.raubach.weatherstation.server.database.codegen.tables.ViewPeriods;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ViewPeriodsRecord extends TableRecordImpl<ViewPeriodsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>weatherstation_db.view_periods.type</code>.
     */
    public void setType(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.type</code>.
     */
    public String getType() {
        return (String) get(0);
    }

    /**
     * Setter for <code>weatherstation_db.view_periods.start_date</code>.
     */
    public void setStartDate(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.start_date</code>.
     */
    public Date getStartDate() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>weatherstation_db.view_periods.end_date</code>.
     */
    public void setEndDate(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.end_date</code>.
     */
    public Date getEndDate() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>weatherstation_db.view_periods.consecutive_days</code>.
     */
    public void setConsecutiveDays(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.consecutive_days</code>.
     */
    public Long getConsecutiveDays() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>weatherstation_db.view_periods.total_rain_amount</code>.
     */
    public void setTotalRainAmount(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>weatherstation_db.view_periods.total_rain_amount</code>.
     */
    public BigDecimal getTotalRainAmount() {
        return (BigDecimal) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ViewPeriodsRecord
     */
    public ViewPeriodsRecord() {
        super(ViewPeriods.VIEW_PERIODS);
    }

    /**
     * Create a detached, initialised ViewPeriodsRecord
     */
    public ViewPeriodsRecord(String type, Date startDate, Date endDate, Long consecutiveDays, BigDecimal totalRainAmount) {
        super(ViewPeriods.VIEW_PERIODS);

        setType(type);
        setStartDate(startDate);
        setEndDate(endDate);
        setConsecutiveDays(consecutiveDays);
        setTotalRainAmount(totalRainAmount);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ViewPeriodsRecord
     */
    public ViewPeriodsRecord(uk.co.raubach.weatherstation.server.database.codegen.tables.pojos.ViewPeriods value) {
        super(ViewPeriods.VIEW_PERIODS);

        if (value != null) {
            setType(value.getType());
            setStartDate(value.getStartDate());
            setEndDate(value.getEndDate());
            setConsecutiveDays(value.getConsecutiveDays());
            setTotalRainAmount(value.getTotalRainAmount());
            resetTouchedOnNotNull();
        }
    }
    // @formatter:on
}
