/*
 * This file is generated by jOOQ.
 */
package uk.co.raubach.weatherstation.server.database.codegen;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import uk.co.raubach.weatherstation.server.database.codegen.tables.Aggregated;
import uk.co.raubach.weatherstation.server.database.codegen.tables.Measurements;
import uk.co.raubach.weatherstation.server.database.codegen.tables.SchemaVersion;


// @formatter:off
/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeatherstationDb extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>weatherstation_db</code>
     */
    public static final WeatherstationDb WEATHERSTATION_DB = new WeatherstationDb();

    /**
     * No further instances allowed
     */
    private WeatherstationDb() {
        super("weatherstation_db", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Aggregated.AGGREGATED,
            Measurements.MEASUREMENTS,
            SchemaVersion.SCHEMA_VERSION
        );
    }
    // @formatter:on
}
